### ISSUE TITLE
Fallback Mode

### ISSUE THREAD

**Issue by coolwanglu** [coolwanglu/pdf2htmlEX#101]
As there are complicated PDF which cannot be handled correctly with pdf2htmlEX.
Or there are too much requirements on the browsers.

There should be a fallback mode, as the ultimate hand.

Basically it's (the traditional) image + hidden text layer, such that we can achieve more precision and better compatibility.

**Comment by rajasuba** [comment]
What is mean by fallback mode? Why do we use it? Could you please explain it...
