### ISSUE TITLE
Option for full-scale output

### ISSUE THREAD

**Issue by zagraves** [coolwanglu/pdf2htmlEX#110]
An option I'd like to see in pdf2htmlEX is one to allow full-scale output. 

Right now pdf2htmlEX will render images at, for example, 2700x2700px @ 300 dpi and then scale down the image in HTML/CSS to fit in a 648x648px box. This option to not scale down the page would mark up the HTML container at 2700x2700px as well. 

I use --split-pages=1 and --single-html=0, so having this option would allow me to have full-scale pages without any negative performance impact on the packaged, single HTML output that is provided by default. 

Something like --no-scale=1 to override the default behaviour would be very helpful.

**Comment by dmitrigur** [comment]
Does the library has functions for images sizing to certain width-height for optimal storage purpose?
