### ISSUE TITLE
Detect and remove duplicated fonts

### ISSUE THREAD

**Issue by Toneti777** [coolwanglu/pdf2htmlEX#117]
In some PDF file, different `fonts` may point to the same `font descriptor` with different `encodings`.
Suppose that the font descriptor contains two glyphs `a` and `b`, one font may specify the encoding `c->a` and `d->b`, but another font may specify `d->a` and `c->b`. PDF viewers may choose correct glyphs to show, while providing correct text for users to select, according to the encodings and tounicode maps, but there's no such mechanisms for HTML.

Generally we have to generate different (re-encoded) fonts such that both rendering and unicode codes are correct, and thus the total file size increases, but in some cases we can be smart to avoid that:
- When both the encoding and tounicode map are compatible (or the product of both mapping are compatible), we can use a single font file
- When we can ignore a set of encoding of tounicode map, we can reencode text for one font according to another (both fonts share the same font descriptor), such that the rendering will be correct but unicode codes are likely to be wrong.

Another case is that there are multiple font descriptors embedded in the PDF file, while they are actually the same fonts. They can be recognized with font comparison function in Fontforge, but I think this is more like a PDF optimizer's job, because no extra space is introduced by pdf2htmlEX.

/// original report
I tried to execute the program with a pdf with some pages. I have a question about the generated font files.
Why the program generates several files for the (in theory) the same font in diferent page?
I've opened the font files and the font name is the same in cases that I've observed the same font type in the output. Is it true or I'm doing something wrong?

Can I do anything to generate only one font file for the same font? For a pdf with a lot of pages this may reduce optimization.

Thanks a lot...

**Comment by Toneti777** [comment]
During the process you generate page by page result.
I think you read the fonts used in each page and add them to result.
You don't check if actually font has already created in previous pages.

I think this is a solution.

**Comment by lmtoo** [comment]
@Toneti777 how do you solve the 
`No glyph for the key character to derive standard width and height.`
problom?
