### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SapraJI** [coolwanglu/pdf2htmlEX#123]
I tried converting this pdf but the program stopped with a segmentation fault

The command used for conversion 
pdf2htmlEX --no-drm 1 --split-pages 1 --embed-external-font 1 --remove-unused-glyph 0 <input-file>

link for the pdf file
https://dl.dropboxusercontent.com/u/1008346/1365165045028c298leigh%40idealadder.com

**Comment by ricardo5401** [comment]
same issue
temporary dir: /tmp/pdf2htmlEX-5AQ8IS
Preprocessing: 6/6
Add new temporary file: /tmp/pdf2htmlEX-5AQ8IS/__css
Add new temporary file: /tmp/pdf2htmlEX-5AQ8IS/__outline
Add new temporary file: /tmp/pdf2htmlEX-5AQ8IS/__pages
Install font 1: (11 0) QYTPFM+ArialNarrow
Add new temporary file: /tmp/pdf2htmlEX-5AQ8IS/f1.ttf
Embed font: /tmp/pdf2htmlEX-5AQ8IS/f1.ttf 1
Add new temporary file: /tmp/pdf2htmlEX-5AQ8IS/__raw_font_1.ttf
em size: 2048
Segmentation fault (core dumped)

pdf2htmlEX version:

pdf2htmlEX version 0.14.6
Copyright 2012-2015 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries:
  poppler 0.33.0
  libfontforge 20171121
  cairo 1.14.6
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg

Ubuntu 16.04.3 LTS,

any ideas?

**Comment by austinnefffo** [comment]
@ricardo5401 Did you find a way around the segmentation fault?

I was having the same issue on Ubuntu 16. I fixed it by installing @coolwanglu's fork of fontforge and rebuilding pdf2htmlEX. 

the fork of fontforge is available here: https://github.com/coolwanglu/fontforge
