### ISSUE TITLE
Cannot compile pdf2htmlEX with GCC 4.7 on Fedora 18

### ISSUE THREAD

**Issue by dove-young** [coolwanglu/pdf2htmlEX#144]
I cannot compile it. Error message said Error: you compiler does not support C++0x, please update it.

But I am got GCC 4.7.2-8.  There is no update package on GCC so far.

15 + 14:07:38 + ~/Shell/pdf2htmlEX
➜   cmake .  
-- checking for module 'libfontforge>=2.0.0'
--   package 'libfontforge>=2.0.0' not found
Trying to locate old versions of fontforge...
Found fontforge.h: /usr/include/fontforge/fontforge.h
Found config.h: /usr/include/fontforge/config.h
Found fontforge: /usr/lib64/libfontforge.so
Looking for libraries of python, which is required by fontforge, if you can link fontforge without python, you may disable this
CMake Error at CMakeLists.txt:138 (message):
  Error: you compiler does not support C++0x, please update it.

-- Configuring incomplete, errors occurred!

16 + 14:10:55 + ~/Shell/pdf2htmlEX
➜   gcc --version
gcc (GCC) 4.7.2 20121109 (Red Hat 4.7.2-8)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

18 + 14:11:41 + ~/Shell/pdf2htmlEX
➜   git status
# On branch master

nothing to commit, working directory clean

19 + 14:11:43 + ~/Shell/pdf2htmlEX
➜   git log | head
commit 3247392c8a8ba5131263e46c1509d8e2e267f474 (HEAD, refs/remotes/origin/master, refs/remotes/origin/HEAD, refs/heads/master)
Author: Lu Wang coolwanglu@gmail.com
Date:   Fri May 10 02:35:54 2013 +0800

```
Update README.md
```

commit 956372c8722ba47d14cdbd56b441939ddc81ae87 (grafted)
Author: Lu Wang coolwanglu@gmail.com
Date:   Thu May 9 23:01:54 2013 +0800

20 + 14:11:51 + ~/Shell/pdf2htmlEX
➜

**Comment by piaolinzhi** [comment]
Someone said that cmake cache made this problem sometimes. It's work for me.
http://stackoverflow.com/questions/26091174/cmake-complaints-about-lack-of-support-of-c0x-of-the-compiler-despite-the-late
