### ISSUE TITLE
--no-drm Segmentation fault: 11

### ISSUE THREAD

**Issue by josh-oiknine** [coolwanglu/pdf2htmlEX#163]
When attempting to convert a file that has copy protection turned on using the --no-drm 1 flag I am getting a Segmentation fault: 11 error. It is not a large file (20 pages) and I even tried to run just the first page.

**Comment by jimmygkr** [comment]
$ pdf2htmlex --zoom 1.3 1.pdf
Preprocessing: 14/14
Segmentation fault: 11
$ pdf2htmlex -v
pdf2htmlEX version 0.13.6
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.37.0
  libfontforge 20151022
  cairo 1.14.2
Default data-dir: /usr/local/Cellar/pdf2htmlex/0.13.6_4/share/pdf2htmlEX
Supported image format: png jpg svg

**Comment by jimmygkr** [comment]
@coolwanglu  segmentation fault: 11,   why

**Comment by Brajendra** [comment]
Preprocessing: 143/143
Warning: encoding confliction detected in font: 1
Fontconfig warning: ignoring UTF-8: not a valid region tag
Segmentation fault: 11
