### ISSUE TITLE
what is the problem?

### ISSUE THREAD

**Issue by allenzhang** [coolwanglu/pdf2htmlEX#212]
# cmake .

-- checking for module 'libfontforge>=2.0.0'
--   package 'libfontforge>=2.0.0' not found
Trying to locate fontforge...
Found fontforge.h: /usr/local/include/fontforge/fontforge.h
Found fontforge: /usr/local/lib/libfontforge.so
Found gunicode: /usr/local/lib/libgunicode.so
Looking for libraries of python, which is required by fontforge, if you can link fontforge without python, you may disable this
-- checking for one of the modules 'python;python-2.7'
Found config.h: /usr/local/include/fontforge/config.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/allen/setup/pdf2htmlEx/pdf2htmlEX_nochk_pdf_protected
# make

Linking CXX executable pdf2htmlEX
/usr/local/lib/libfontforge.so: undefined reference to `PyTuple_SetItem'
/usr/local/lib/libfontforge.so: undefined reference to`PyObject_SelfIter'
/usr/local/lib/libfontforge.so: undefined reference to `PyExc_ValueError'
/usr/local/lib/libfontforge.so: undefined reference to`PyMem_Realloc'
/usr/local/lib/libfontforge.so: undefined reference to `PyBool_Type'
/usr/local/lib/libfontforge.so: undefined reference to`PyString_AsStringAndSize'
/usr/local/lib/libfontforge.so: undefined reference to `PyExc_KeyError'
/usr/local/lib/libfontforge.so: undefined reference to`_Py_TrueStruct'
/usr/local/lib/libfontforge.so: undefined reference to `PyObject_GetAttrString'
/usr/local/lib/libfontforge.so: undefined reference to`_Py_ZeroStruct'
/usr/local/lib/libfontforge.so: undefined reference to `PyExc_EnvironmentError'
/usr/local/lib/libfontforge.so: undefined reference to`PyMem_Free'
/usr/local/lib/libfontforge.so: undefined reference to `PyType_IsSubtype'
/usr/local/lib/libfontforge.so: undefined reference to`PyModule_AddObject'
/usr/local/lib/libfontforge.so: undefined reference to `PyRun_SimpleStringFlags'
/usr/local/lib/libfontforge.so: undefined reference to`PyTuple_New'
/usr/local/lib/libfontforge.so: undefined reference to `_Py_NoneStruct'
/usr/local/lib/libfontforge.so: undefined reference to`PyExc_AttributeError'
/usr/local/lib/libfontforge.so: undefined reference to `PyDict_SetItemString'
/usr/local/lib/libfontforge.so: undefined reference to`PyType_Type'
/usr/local/lib/libfontforge.so: undefined reference to `PyMapping_Check'
/usr/local/lib/libfontforge.so: undefined reference to`PyString_AsEncodedObject'
/usr/local/lib/libfontforge.so: undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/local/lib/libfontforge.so: undefined reference to`PyTuple_Size'
/usr/local/lib/libfontforge.so: undefined reference to `_PyObject_New'
/usr/local/lib/libfontforge.so: undefined reference to`PyErr_Format'
/usr/local/lib/libfontforge.so: undefined reference to `PyFloat_FromDouble'
/usr/local/lib/libfontforge.so: undefined reference to`PyFloat_AsDouble'
/usr/local/lib/libfontforge.so: undefined reference to `Py_Main'
/usr/local/lib/libfontforge.so: undefined reference to`PyString_FromString'
/usr/local/lib/libfontforge.so: undefined reference to `PyMem_Malloc'
/usr/local/lib/libfontforge.so: undefined reference to`Py_BuildValue'
/usr/local/lib/libfontforge.so: undefined reference to `PyExc_NameError'
/usr/local/lib/libfontforge.so: undefined reference to`PySequence_Check'
/usr/local/lib/libfontforge.so: undefined reference to `PyString_FromStringAndSize'
/usr/local/lib/libfontforge.so: undefined reference to`PyErr_Clear'
/usr/local/lib/libfontforge.so: undefined reference to `Py_InitModule4_64'
/usr/local/lib/libfontforge.so: undefined reference to`PyMapping_GetItemString'
/usr/local/lib/libfontforge.so: undefined reference to `PyDict_New'
/usr/local/lib/libfontforge.so: undefined reference to`PyUnicodeUCS4_DecodeUTF8'
/usr/local/lib/libfontforge.so: undefined reference to `PyErr_SetString'
/usr/local/lib/libfontforge.so: undefined reference to`Py_SetProgramName'
/usr/local/lib/libfontforge.so: undefined reference to `PyDict_Update'
/usr/local/lib/libfontforge.so: undefined reference to`PyExc_NotImplementedError'
/usr/local/lib/libfontforge.so: undefined reference to `PyString_FromFormat'
/usr/local/lib/libfontforge.so: undefined reference to`PyArg_ParseTuple'
/usr/local/lib/libfontforge.so: undefined reference to `PyInt_AsLong'
/usr/local/lib/libfontforge.so: undefined reference to`PyRun_SimpleFileExFlags'
/usr/local/lib/libfontforge.so: undefined reference to `PyObject_Free'
/usr/local/lib/libfontforge.so: undefined reference to`PyExc_TypeError'
/usr/local/lib/libfontforge.so: undefined reference to `PyType_Ready'
/usr/local/lib/libfontforge.so: undefined reference to`PyEval_CallObjectWithKeywords'
/usr/local/lib/libfontforge.so: undefined reference to `PySequence_GetItem'
/usr/local/lib/libfontforge.so: undefined reference to`PySequence_Size'
/usr/local/lib/libfontforge.so: undefined reference to `PyObject_CallMethod'
/usr/local/lib/libfontforge.so: undefined reference to`PyErr_Occurred'
/usr/local/lib/libfontforge.so: undefined reference to `PyFloat_Type'
/usr/local/lib/libfontforge.so: undefined reference to`PyCallable_Check'
/usr/local/lib/libfontforge.so: undefined reference to `PyExc_ImportError'
/usr/local/lib/libfontforge.so: undefined reference to`PyString_AsString'
/usr/local/lib/libfontforge.so: undefined reference to `PyMapping_HasKeyString'
/usr/local/lib/libfontforge.so: undefined reference to`PyRun_InteractiveLoopFlags'
/usr/local/lib/libfontforge.so: undefined reference to `PyInt_FromLong'
/usr/local/lib/libfontforge.so: undefined reference to`Py_Initialize'
/usr/local/lib/libfontforge.so: undefined reference to `PyErr_Print'
/usr/local/lib/libfontforge.so: undefined reference to`PyTuple_GetItem'
/usr/local/lib/libfontforge.so: undefined reference to `PyImport_AppendInittab'
/usr/local/lib/libfontforge.so: undefined reference to`PyUnicodeUCS4_AsUTF8String'
/usr/local/lib/libfontforge.so: undefined reference to `PyString_Decode'
collect2: ld returned 1 exit status
make[2]: **\* [pdf2htmlEX] Error 1
make[1]: **\* [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: **\* [all] Error 2

**Comment by vipul-todeveloper** [comment]
Hi.. i am having same issue and for error, wiki says "undefined reference of Py_xxx, install header files of python-2.x".

/usr/local/lib/libfontforge.so: undefined reference to `PyString_Decode'
collect2: error: ld returned 1 exit status
make[2]: *** [pdf2htmlEX] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2

But i am not getting what will actually fix my issue. can any body give me command to fix this above error?

Thanks in advance,
Vipul
