### ISSUE TITLE
Add GUI to use search API

### ISSUE THREAD

**Issue by rvanlaak** [coolwanglu/pdf2htmlEX#232]
In #231 an API has been introduced to search in the result html. When this API works, the next step could be to add an GUI that makes use of this API.

The GUI should contain form elements to feed the search-API with data. A first version could have two tabs, one for `search` and one for `search & replace`. Both tabs can contain radio buttons for the search method (`regular` vs. `regex`) and search direction (`up` vs. `down`)

**Comment by BockwurstJoe** [comment]
I am looking for a reader/viewer application as descibed here: https://github.com/coolwanglu/pdf2htmlEX/issues/219 has there been any effort since the issue was closed? I was trying really hard to implement one by myself but I am struggling with displaying it right on many devices.
