### ISSUE TITLE
Fit window width on load

### ISSUE THREAD

**Issue by MarcGodard** [coolwanglu/pdf2htmlEX#249]
I can't seem to find this, forgive me if it already exists.

@coolwanglu This is a beautiful library, thank you very much. However, I would like to know if I can make the html file fit width on load. So when I open them up in a browser, they resize immediately to fit the width of the window.

I would make them with --zoom 2 to make sure they are large enough to keep quality.

Any suggestions? I thought added an onload event that changes the scale would work, but having difficulties.

**Comment by timgallengor** [comment]
Could you explain a little more how to implement this, for example on the demo of -
http://coolwanglu.github.io/pdf2htmlEX/demo/cheat.html  ?

I am trying to get the page (not the background) widths to adjust according to the window size. I also need to be able to do this across a large number of converted pdfs. Thanks for any help!
