### ISSUE TITLE
Rendering problems in Chrome

### ISSUE THREAD

**Issue by sathomas** [coolwanglu/pdf2htmlEX#259]
This could be related to #258 but it happens in Chrome rather than Safari. Looking at this document: http://www.mediafire.com/view/19v6y3g8r9cwm1h/Lipsum(2).pdf at the bottom of the first page.

In Preview.app:

![screen shot 2013-12-03 at 2 58 55 pm](https://f.cloud.github.com/assets/1731910/1667426/622e9548-5c55-11e3-9142-6bd41abe4121.png)

Rendered in Chrome 31:

![screen shot 2013-12-03 at 2 55 44 pm](https://f.cloud.github.com/assets/1731910/1667429/6e3957ec-5c55-11e3-86a9-8cac9e38165e.png)

Note that if the `span { display: inline-block; }` rule in `base.css` is disabled, the rendering is fine:

![screen shot 2013-12-03 at 2 56 27 pm](https://f.cloud.github.com/assets/1731910/1667435/877e239a-5c55-11e3-8b72-c5db12a314ba.png)

I'm not sure of the purpose of that rule, so I can't say what the implications are for the rest of the document

**Comment by sporritt** [comment]
@coolwanglu Sorry to resurrect a closed issue, but would you happen to know which version of pdf2htmlex this went into?  I see what I think is the error described in this issue on this document (page 5 shows one example) on Chrome in Windows:

http://www.mediafire.com/view/03jt3v2qk7rp9zk/2012-0427_Clorox_Building_F_-_IFC_Specifications_(1).pdf

...but maybe it was processed with a version of the code before this fix went in?  I can't tell.

thanks.

**Comment by coolwanglu** [comment]
@sporritt No I'm not sure. You may try the latest version of pdf2htmlEX.
