### ISSUE TITLE
Internal Error: Attempt to output 2147483647 into a 16-bit field. it will be truncated and the file may not be useful

### ISSUE THREAD

**Issue by sharemu** [coolwanglu/pdf2htmlEX#279]
我今天再一次 在windows 7 64位操作系统上，调用pdf2htmlex 发生了"Internal Error: Attempt to output 2147483647 into a 16-bit field. it will be truncated and the file may not be useful "
错误，我需要从哪几个方面检查 我的系统环境？能给点帮助么？

**Comment by KIONAPAC** [comment]
> 我今天再一次 在windows 7 64位操作系统上，调用pdf2htmlex 发生了"Internal Error: Attempt to output 2147483647 into a 16-bit field. it will be truncated and the file may not be useful "
> 错误，我需要从哪几个方面检查 我的系统环境？能给点帮助么？

我猜是不是你的账号权限不足以访问生成字体的目录？
