### ISSUE TITLE
Syntax Warning: May not be a PDF file (continuing anyway) .

### ISSUE THREAD

**Issue by shivnarayans** [coolwanglu/pdf2htmlEX#295]
1. the file on which i am working is pdf , but is having this issue, could you please tell me how to fix this one. 
   link to pdf 'http://www.siemens.com/investor/pool/en/investor_relations/financial_publications/speeches_and_presentations/q42011/q4_fy2011_analyst_presentation.pdf

Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error (4): Illegal character <21> in hex string
Syntax Error (6): Illegal character <4f> in hex string
Syntax Error (8): Illegal character <54> in hex string
Syntax Error (9): Illegal character <59> in hex string
Syntax Error (10): Illegal character <50> in hex string
..
..
..
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Error: Cannot read the file
1. apart from this i am also getting Core Dumped for many files. 
   i am working with pdf2htmlex .11 
   fontforge 20140121 (latest from github)

**Comment by jjhesk** [comment]
same here!

**Comment by goerlitzer** [comment]
same here too!

**Comment by aryan-solo** [comment]
is there any solution!
here is my error.
here we run subprcess to convert pdf to searchable text!
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

**Comment by Kirink212** [comment]
I'm having the same problem. I don't even know how to debug it!! :'(

**Comment by aryan-solo** [comment]
In my case the PDF was not serachable that is it was a scanned PDF
