### ISSUE TITLE
PPA outdated packages

### ISSUE THREAD

**Issue by crspl** [coolwanglu/pdf2htmlEX#310]
Any chances to get updated packages in PPA?

**Comment by Siddhant** [comment]
@coolwanglu A Utopic package for fontforge is now available. Can you now try to upload a Ubuntu Utopic package for pdf2htmlEX ?

**Comment by MarcGodard** [comment]
Is there a PPA for this again yet?

**Comment by egrubbs** [comment]
You can try https://launchpad.net/~edwin-grubbs/+archive/ubuntu/ppa for trusty. It also updates poppler, pdf.js and fontforge.
