### ISSUE TITLE
Issue with libfontforge.

### ISSUE THREAD

**Issue by suchee** [coolwanglu/pdf2htmlEX#327]
I am having issues with the libfontforge on mac. I installed the libfontforge using the macports. I am certain that fontforge is installed on my machine. The cmake log is attached. Can you please help?

-- The C compiler identification is Clang 5.1.0
-- The CXX compiler identification is Clang 5.1.0
-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28") 
-- checking for module 'poppler>=0.25.0'
--   package 'poppler>=0.25.0' not found
-- checking for module 'poppler>=0.23.0'
--   found poppler, version 0.24.5
-- checking for module 'libfontforge>=2.0.0'
--   package 'libfontforge>=2.0.0' not found
CMake Error at /opt/local/share/cmake-2.8/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/local/share/cmake-2.8/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:75 (pkg_check_modules)

-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring incomplete, errors occurred!

**Comment by raisen** [comment]
I was having the same issue suchee was having on his first post. So I downloaded coolwanglu's forked version of fontforge, but I'm getting an error when compiling it:

bootstrap: running: autoreconf --symlink --install
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4: unrecognized option `--gnu'
Try `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gm4 --help' for more information.
autom4te: gm4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

It's looking like an incompatibility with a newer version of Xcode, but not sure how to proceed from here.

**Comment by paxperscientiam** [comment]
@suchee suggestion is exactly what I needed (thanks btw).

> environment variables I set on Mac.
> export LIBRARY_PATH=/usr/local/lib
> export LD_LIBRARY_PATH=/usr/local/lib
> export INCLUDE_PATH=/usr/local/include
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

@coolwanglu, was this ever addressed? I just successfully built `v0.14.6` with the above vars set.
