### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by lystor** [coolwanglu/pdf2htmlEX#333]
Hi, coolwanglu

Please fix segfaults.

pdf2htmlex snapshot 20140323

fontforge 2.0.20140101
https://github.com/fontforge/fontforge/releases

ftp://ftp.dlink.ru/pub/Switch/DES-1210-28_ME_B2/Description/DES-1210-10ME_26ME_28ME%20Rev.B2%20User%20Manual%20R6.02.pdf

ftp://ftp.dlink.ru/pub/Switch/DES-1210-28_ME_B2/Description/DES-1210-10ME_26ME_28ME%20Rev.B2%20CLI%20Guide%20R6.02.pdf

ftp://ftp.dlink.ru/pub/Printserver/DPR-1061/Description/DPR-1061_QIG_EST.pdf

ftp://ftp.dlink.ru/pub/usb/DWM-157/Description/D-Link%20DWM-157%20Linux%20guide.pdf

$ pdf2htmlEX --debug 1 DES-1210-10ME_26ME_28ME\ Rev.B2\ CLI\ Guide\ R6.02.pdf 
temporary dir: /tmp/pdf2htmlEX-28Erg8
Preprocessing: 370/370
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__css
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__outline
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__pages
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/bg1.png
Install font 1: (6 0) Times New Roman
Embed font: /usr/share/fonts/default/Type1/n021003l.pfb 1
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__raw_font_1.pfb
em size: 1000
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f1.map
space width: 0.25
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__tmp_font1.ttf
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__tmp_font2.ttf
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f1.woff
Install font 2: (8 0) Arial
Embed font: /usr/share/fonts/default/Type1/n019003l.pfb 2
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__raw_font_2.pfb
em size: 1000
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f2.map
space width: 0.278
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f2.woff
Install font 3: (10 0) ABCDEE+Arial Unicode MS
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f3.ttf
Embed font: /tmp/pdf2htmlEX-28Erg8/f3.ttf 3
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'LTSH' linear threshold table
  Ignoring 'hdmx' horizontal device metrics table
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/__raw_font_3.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-28Erg8/f3.map
space width: 0.278
Segmentation fault

$ pdf2htmlEX --debug 1 DES-1210-10ME_26ME_28ME\ Rev.B2\ User\ Manual\ R6.02.pdf 
temporary dir: /tmp/pdf2htmlEX-x9WBcK
Preprocessing: 129/129
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__css
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__outline
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__pages
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/bg1.png
Install font 1: (6 0) Arial
Embed font: /usr/share/fonts/default/Type1/n019003l.pfb 1
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__raw_font_1.pfb
em size: 1000
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/f1.map
space width: 0.278
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__tmp_font1.ttf
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__tmp_font2.ttf
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/f1.woff
Install font 2: (8 0) ABCDEE+Arial Unicode MS
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/f2.ttf
Embed font: /tmp/pdf2htmlEX-x9WBcK/f2.ttf 2
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'LTSH' linear threshold table
  Ignoring 'hdmx' horizontal device metrics table
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/__raw_font_2.ttf
em size: 2048
Add new temporary file: /tmp/pdf2htmlEX-x9WBcK/f2.map
space width: 0.278
Segmentation fault
## 

With best regards,
Nikolay

**Comment by lmtoo** [comment]
我也遇到这个问题了，请问这个问题怎么解决的？

**Comment by AroojPerzada** [comment]
@coolwanglu I'm working with the linux enviornment 16.04 LTS and I compiled my pdf2htmlEX from this site: https://github.com/fmalina/transcript
and ran this command: brew install python3 pdf2htmlEX but when i run my file it keeps saying 
No glyph for the key character to derive standard width and height.
For the latin script, this key character is `o' (U+006F).
Lookup 'mark' Mark Positioning lookup 7 has an
offset bigger than 65535 bytes. This means
FontForge must use an extension lookup to output it.
Not all applications support extension lookups.
Internal Error: assembly tables at wrong place
Is this font forge error and how to resolve this?

**Comment by ltg001** [comment]
it seems to happen because the output file is bigger than 65535 bytes
