### ISSUE TITLE
wrong dimensions of background images for svg format

### ISSUE THREAD

**Issue by crspl** [coolwanglu/pdf2htmlEX#335]
Hi,

When converting some non-standard sized pdfs with bg-format = svg, dimensions of background images are wrong. Well, not dimensions of canvas but image is zoomed out. Look at the screenshoot:
https://www.dropbox.com/s/3df5dxhez7k94jo/test_pdf_to_jpg_svg.jpg
Version with jpg format for background is on the left, and svg on the right.

Converted with the latests version of pdf2htmlex compiled from sources with cairo 1.12.16 and poppler 0.24.5

Command line used for conversion:
- jpg version: pdf2htmlEX test.pdf
- svg version: pdf2htmlEX --bg-format svg test.pdf

PDF file: https://www.dropbox.com/s/g6ckyzvqs3hyims/test.pdf
Converted file (jpeg): https://www.dropbox.com/s/tnmbdk546a3lcbr/test_jpg.html
Converted file (svg): https://www.dropbox.com/s/2pr4lydoknktc48/test_svg.html

**Comment by coolwanglu** [comment]
Fixed in `incoming`.
