### ISSUE TITLE
more semantic html

### ISSUE THREAD

**Issue by siemenbaader** [coolwanglu/pdf2htmlEX#348]
Hi Coolwanglu,

pdf2htmlEX is great, thanks for building it!

I'm using it together with the Chrome readline extension [1] to read pdf documents, but the extension is having a hard time with the generated markup. Would you consider generating more semantic html, ie <p>  for paragraphs and no <span>s for spaces?

1: https://chrome.google.com/webstore/detail/readline/hjbkmfadmomgaokjodomncmbgmmodona?hl=en

**Comment by fmalina** [comment]
You might want to look at https://github.com/fmalina/transcript, a post processing tool for PDFtoHMLEx output providing semantic HTML based on visual design conventions.
