### ISSUE TITLE
ffglib.h:27:18: error: glib.h: No such file or directory

### ISSUE THREAD

**Issue by rinox14** [coolwanglu/pdf2htmlEX#386]
Hi Coolwanglu,
I install pdf2htmlEX on CentOS 6.5 x64 with popper 0.26 and fontforge use your fork https://github.com/coolwanglu/fontforge/tree/pdf2htmlEX but i having issues:

[root@localhost pdf2htmlEX-master]# export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
[root@localhost pdf2htmlEX-master]# cmake .
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'poppler>=0.25.0'
--   found poppler, version 0.26.2
-- checking for module 'libfontforge>=2.0.0'
--   found libfontforge, version 2.0.20140101
-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/pdf2htmlEX-master

[root@localhost pdf2htmlEX-master]# make
[  3%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/pdf2htmlEX.cc.o
[  6%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/draw.cc.o
[ 10%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o
[ 13%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/image.cc.o
[ 16%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/link.cc.o
[ 23%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/outline.cc.o
[ 26%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/state.cc.o
[ 30%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/text.cc.o
[ 33%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/BackgroundRenderer.cc.o
[ 36%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/SplashBackgroundRenderer.cc.o
[ 40%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/CairoBackgroundRenderer.cc.o
[ 43%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/const.cc.o
[ 46%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/encoding.cc.o
[ 50%] Building C object CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o
In file included from /usr/include/fontforge/baseviews.h:30,
                 from /usr/src/pdf2htmlEX-master/src/util/ffw.c:17:
/usr/include/fontforge/ffglib.h:27:18: error: glib.h: No such file or directory
/usr/include/fontforge/ffglib.h:28:25: error: glib-object.h: No such file or directory
In file included from /usr/src/pdf2htmlEX-master/src/util/ffw.c:17:
/usr/include/fontforge/baseviews.h:78: error: expected specifier-qualifier-list before âGList_Glibâ
make[2]: **\* [CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o] Error 1
make[1]: **\* [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: **\* [all] Error 2

=> I have installed glib header:
[root@localhost pdf2htmlEX-master]# locate glib.h
/usr/include/jpeglib.h
/usr/include/fontforge/ffglib.h
/usr/include/glib-2.0/glib.h
/usr/share/gtk-doc/html/glib/glib.html
/usr/src/fontforge-pdf2htmlEX/fontforge/ffglib.h
/usr/src/glib-2.38.2/docs/reference/glib/html/glib.html
/usr/src/glib-2.38.2/glib/glib.h
/usr/src/pkg-config-0.28/glib/glib/glib.h

[root@localhost pdf2htmlEX-master]# locate glib.h
/usr/include/jpeglib.h
/usr/include/fontforge/ffglib.h
/usr/include/glib-2.0/glib.h
/usr/share/gtk-doc/html/glib/glib.html
/usr/src/fontforge-pdf2htmlEX/fontforge/ffglib.h
/usr/src/glib-2.38.2/docs/reference/glib/html/glib.html
/usr/src/glib-2.38.2/glib/glib.h
/usr/src/pkg-config-0.28/glib/glib/glib.h
[root@localhost pdf2htmlEX-master]# locate glib-object.h
/usr/include/glib-2.0/glib-object.h
/usr/src/glib-2.38.2/glib/glib-object.h
/usr/src/pkg-config-0.28/glib/glib/glib-object.h

Can you please help me?

Thanks.

**Comment by ayuan124** [comment]
- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- checking for module 'poppler>=0.25.0'
--   found poppler, version 0.45.0
-- checking for module 'libfontforge>=2.0.0'
--   found libfontforge, version 2.0.20140101
-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/opt/pdf2html/pdf2htmlEX-master
[root@localhost pdf2htmlEX-master]# make
Scanning dependencies of target pdf2htmlEX
[  3%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/pdf2htmlEX.cc.o
[  6%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/draw.cc.o
[  9%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o
[ 12%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/image.cc.o
[ 15%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o
[ 18%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/form.cc.o
[ 21%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/link.cc.o
[ 24%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/outline.cc.o
[ 27%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/state.cc.o
[ 30%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/text.cc.o
[ 33%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/BackgroundRenderer.cc.o
[ 36%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/SplashBackgroundRenderer.cc.o
[ 39%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/CairoBackgroundRenderer.cc.o
[ 42%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/const.cc.o
[ 45%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/encoding.cc.o
[ 48%] Building C object CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o
在包含自 /usr/include/fontforge/baseviews.h：30 的文件中，
                 从 /home/opt/pdf2html/pdf2htmlEX-master/src/util/ffw.c：17:
/usr/include/fontforge/ffglib.h:27:18: 错误：glib.h：没有那个文件或目录
/usr/include/fontforge/ffglib.h:28:25: 错误：glib-object.h：没有那个文件或目录
In file included from /home/opt/pdf2html/pdf2htmlEX-master/src/util/ffw.c:17:
/usr/include/fontforge/baseviews.h:78: 错误：expected specifier-qualifier-list before ‘GList_Glib’
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o] 错误 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by marsty** [comment]
@lyphandl can tell me how to fix it ? thanks~
