### ISSUE TITLE
SVG scaling/clipping/positioning issues

### ISSUE THREAD

**Issue by davidhedley** [coolwanglu/pdf2htmlEX#402]
When using --bg-format svg, the background SVG image is sometimes not scaled/positioned/clipped correctly. The attached ZIP file contains some test cases. All these render fine when using --bg-format png

Test cases here:
http://download.vistair.com/pdf2htmlEX/SVGScalingClipping.zip

Version info:
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributors
Libraries:
poppler 0.26.3
libfontforge 20140801
cairo 1.13.1
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg

**Comment by coolwanglu** [comment]
Seems to be fixed. Cannot remember which commit though (or maybe in poppler).

**Comment by coolwanglu** [comment]
Oh wait, it's not fixed. I made a mistake.

**Comment by coolwanglu** [comment]
Right. I've included the fix in `incoming`. Can I use any PDF in that zip for a test case?

**Comment by davidhedley** [comment]
Yes of course

Best wishes
David

Sent from my iPhone

On 3 May 2015, at 07:22, Lu Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Right. I've included the fix in incoming. Can I use any PDF in that zip for a test case?

-

**Comment by coolwanglu** [comment]
Thanks.
And sorry for the long delay btw. I've been quite busy.

**Comment by coolwanglu** [comment]
test case added.
