### ISSUE TITLE
pdf2htmlEX v0.12 compiling issues with CentOS 6.5

### ISSUE THREAD

**Issue by itsjamil** [coolwanglu/pdf2htmlEX#409]
After compiling all depending modules, getting following errors while compiling pdf2htmlEX v0.12:

`-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'poppler>=0.25.0'
--   found poppler, version 0.25.0
-- checking for module 'libfontforge>=2.0.0'
--   found libfontforge, version 2.0.20140101
-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/code/pdf2htmlEX-0.12
Scanning dependencies of target pdf2htmlEX
[  3%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/pdf2htmlEX.cc.o
[  6%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/draw.cc.o
[  9%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc: In constructor ‘pdf2htmlEX::HTMLRenderer::HTMLRenderer(const pdf2htmlEX::Param&)’:
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:83: error: expected primary-expression before ‘[’ token
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:83: error: expected primary-expression before ‘double’
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:83: error: expected ‘;’ before ‘{’ token
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:85: error: expected primary-expression before ‘[’ token
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:85: error: expected primary-expression before ‘double’
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:85: error: expected primary-expression before ‘bool’
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:85: error: expected ‘;’ before ‘{’ token
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:87: error: expected primary-expression before ‘[’ token
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:87: error: expected primary-expression before ‘double’
/tmp/code/pdf2htmlEX-0.12/src/HTMLRenderer/general.cc:87: error: expected ‘;’ before ‘{’ token
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Whinza** [comment]
Hello I am trying to compile but I getting error during linking
[root@hurricane pdf2htmlEX]# make
Trying to locate cairo-svg...
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/pdf2htmlEX
Linking CXX executable pdf2htmlEX
/usr/bin/ld: cannot find -lfontforge
collect2: error: ld returned 1 exit status
make[2]: *** [pdf2htmlEX] Error 1
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
