### ISSUE TITLE
Negative word spacing

### ISSUE THREAD

**Issue by afrosimon** [coolwanglu/pdf2htmlEX#416]
I've encountered a case of negative word spacing inside of a specific page, and it screws over the layout quite bad. It can be observed in chrome and not firefox.

Here is the sample : 
https://dl.dropboxusercontent.com/u/7037559/negative-word-spacing.zip

pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.26.2
  libfontforge 20140717
  cairo 1.13.1
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg

**Comment by coolwanglu** [comment]
@afrosimon Seems that it's been fixed via #484. Can you verify this? Also is it ok to use this file as a test case in pdf2htmlEX?

**Comment by afrosimon** [comment]
Yup everything's fine on my end. Also yes you can use the file I've
provided for the test case.
