### ISSUE TITLE
text is not positioned correctly

### ISSUE THREAD

**Issue by razamobin** [coolwanglu/pdf2htmlEX#421]
Hi there, I have a sample PDF where one line of text on page 2 is rendered on top of text on the next line, which makes the text unreadable. 

This is only in some browser/OS environments.

broken: 
1. Mac OS X 10.9.4 Chrome 36.0.1985.143
correct output: 
1. Ubuntu 10.04 Chromium 25.0.1364.160
2. Ubuntu 10.04 FireFox 20.0

This is using pdf2htmlEX version 0.12 (latest at this time), and can be reproduced with adding no command line args to the command. 

pdf:
https://dl.dropboxusercontent.com/u/31309918/dd/201408/pMkF050fEI.pdf

html:
https://dl.dropboxusercontent.com/u/31309918/dd/201408/pMkF050fEI.html

screenshot of bug is attached
![pdf2htmlbug](https://cloud.githubusercontent.com/assets/502970/4037987/a006743a-2cac-11e4-87cf-ada07ecc1101.jpg)

**Comment by coolwanglu** [comment]
Should have been fixed.
