### ISSUE TITLE
PDF fails to convert with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by apond** [coolwanglu/pdf2htmlEX#435]
The file AvondaleTimes2012.pdf has been uploaded to MediaFire.  The output is as follows:
Preprocessing: 0/4
Preprocessing: 1/4
Preprocessing: 2/4
Preprocessing: 3/4
Preprocessing: 4/4

Working: 0/4
Process finished with exit code -1073741819 (0xC0000005)

The command used was:
pdf2htmlEX --zoom 1 --embed cfijo --split-pages 1 --dest-dir' out --page-filename page%d.xhtml AvondaleTimes2012.pdf

pdf2htmlEX version 0.11

**Comment by coolwanglu** [comment]
I see only a epub file there. Please try the latest `incoming` branch.
If the problem still exists, please upload the file again and provide a link here.
