### ISSUE TITLE
Create thumbnails from PDF pages

### ISSUE THREAD

**Issue by sathishks** [coolwanglu/pdf2htmlEX#439]
Hi,

Is there a any Options to create thumbnails from PDF pages to help navigation between pages ?

 pdf2htmlEX -v
 pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributers
Libraries:
  poppler 0.25.0
  libfontforge 20140221
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

Thanks,
Sathish Kumar S

**Comment by gabrieltong** [comment]
@coolwanglu where can I find `pdftocairo` ?
