### ISSUE TITLE
Ubuntu 12.04: pdf2htmlEX: error while loading shared libraries: libfontforge.so.2

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#451]
pdf2htmlEX: error while loading shared libraries: libfontforge.so.2: cannot open shared object file: No such file or directory

From stock coolwanglu PPA install.  System update my have triggered it.  Crippling our production environment now - I hope there's a solution for this or a 14.04 PPA compatibility coming :(

**Comment by eric-brechemier** [comment]
It is not fixed: I also experienced this issue on Ubuntu 12.04 after installing pdf2htmlEX from the Ubuntu PPA today.

**Comment by eric-brechemier** [comment]
Note: I had `fontforge` already installed on the system:

```sh
$  dpkg -l | grep fontforge
ii  fontforge                              0.0.20110222-4ubuntu1                          font editor
ii  libfontforge1                          0.0.20110222-4ubuntu1                          font editor - runtime library
```

**Comment by eric-brechemier** [comment]
Installing `libfontforge-dev` solved the issue for me too:

```sh
$ sudo apt-get install libfontforge-dev
```

**Comment by eric-brechemier** [comment]
Note: after installing `libfontforge-dev`:

```sh
$ dpkg -l | grep fontforge
ii  fontforge                              20141014-0ubuntu1~precise               font editor
ii  fontforge-common                       20141014-0ubuntu1~precise               font editor (common files)
ii  libfontforge1                          20141014-0ubuntu1~precise               font editor - runtime library
```

It seems that `fontforge-common` was the missing requirement.

**Comment by rajeevkannav** [comment]
```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```
#145
