### ISSUE TITLE
pdf2htmlEX High CPU maximization on centos 6.4

### ISSUE THREAD

**Issue by sathishks** [coolwanglu/pdf2htmlEX#454]
Hi ,
pdf2htmlEX --split-pages 1 --fit-width 800 2_RogueTrader.pdf 

Below pdf file is convert successfully, but this pdf file take it high cpu 99% and memory 1.4% . 

how to resolve the high cpu 99 %  ??

https://www.dropbox.com/s/h84f4sqdql1i26h/2_RogueTrader.pdf?dl=0

version info:

pdf2htmlEX -v
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributers
Libraries:
  poppler 0.25.0
  libfontforge 20140221
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

**Comment by coolwanglu** [comment]
I can reproduce it. Yet given the size of the pdf file, especially the image with high resolutions, I don't think the cpu usage is too high.
