### ISSUE TITLE
Some hyperlinks not working.

### ISSUE THREAD

**Issue by nboisteault** [coolwanglu/pdf2htmlEX#462]
I've converted this pdf : http://symfony.com/pdf/Symfony_book_2.5.pdf?v=4 on my ubuntu 12.04 with pdf2htmlEX installed via your ppa and default parameters .Some hyperlinks are not working like on page 6 at the bottom.
I've also tried on mediafire : http://www.mediafire.com/view/4aoc5i61o6wn87c/Symfony_book_2.5_fr.pdf

The result is the same.

Thank you for your nice work!

**Comment by coolwanglu** [comment]
I cannot reproduce it. Please try the latest `incoming` branch.
