### ISSUE TITLE
Issue with rendering svg with embedded bitmaps on safari

### ISSUE THREAD

**Issue by bilalmughal** [coolwanglu/pdf2htmlEX#464]
While using svg for background, i noticed that the images embedded in svg are not displayed in safari.
After doing some searching i end up on this [stackoverflow answer](http://stackoverflow.com/a/27128309)

It says  
> If you use \<img\> tags, then **`webkit based browsers won't display embedded bitmapped images.`**

This answer also suggest, which i agree to as well

> I have found that the \<object\> tag is the only one that works across all browsers.

My requirement was to support safari as well, and svg should be embeded to html. So i end up adding option `--svg-use-object-tag` and replaced \<img\> tag with \<object\>. So @coolwanglu  if you think, this option should be in there and will be useful to others who want to use svgs with embedded bitmaps on safari, i can send a pull request or post a patch.

> ### Non Safari Browser Output
![Non Safari](https://ritpda.dm2302.livefilestore.com/y2m4h-kJOxtD5tqT2z01CpxUYMXMUJ_El62CEy5SPGJveEW5GvqbDk5q-OzJ_TvHH9WUA2YzVyNMXpF4x2_mmfU4pPWKIV0Nhm2E8qDd1oq4N7xZp_l5kahPzFgCkkXKO-NV0iqrYAZvP88kDcIPgubH02dAZQpW0fj7EpLOA4OhZU/svg-non-safari.png?psid=1)

and 

> ### Safari Output
![Safari](https://rise6q.dm2302.livefilestore.com/y2mlFofTMurnM3GqGhScZbaX3HJ02Xnjv0lxoDCmGmaeyCUrvfWClUUML_tvVYVGqe3VUrdQBER-FbWGHqL9IE4mo4Bm9-BLDq3pxLeu8RPdaoyc-2H8pI4gqENyGc9Zg44nDymK9Pr0G583quBmI6o52eclqpkG7yxOjYc_QqjoOQ/svg-non-safari.png.png?psid=1)

Output html file can be download from [here](http://1drv.ms/1w1lcSK)

**Comment by duanyao** [comment]
These bitmap is embeded in the svg via data: url, while the svg is refed by the html via `<img>`.
In this case, webkit doesn't show the bitmap, while Chrome (uses blink, a fork of webkit) works fine.

This is obviously a bug of webkit (https://bugs.webkit.org/show_bug.cgi?id=99677). Because a fix is in progress in webkit, I think there is no need to add `--svg-use-object-tag`.

As a workaround, you can try `--svg-embed-bitmap 0`, and you must make sure the bitmaps in your pdfs are in jpeg format and in RGB or Gray colorspace.

**Comment by bilalmughal** [comment]
I don't think that is viable in my case to use `--svg-embed-bitmap 0` and source pdfs are from different sources so there is no way I can make sure  that bitmaps used in pdfs are in jpeg format.
 
We don't know when this fix will be shipped and even after the bug is fixed we can not expect all browsers to get updated over night, so in a way it is good to use `\<object\>` tag for svg, at least  for backward compatibility sake.

Atleast I have to stick with this option, so i thought there must be people who have similar requirements like me.

**Comment by duanyao** [comment]
>there is no way I can make sure that bitmaps used in pdfs are in jpeg format.

You can use Ghostscript or Adobe Acrobat to convert all bitmaps in pdfs to jpeg. Actually our team do this.

<object> or <embed> are more expensive than <img>, because browsers create nested browsing contexts for them, so we use <img> where possible.

**Comment by bilalmughal** [comment]
I can go through this preprocessing process did not know `Ghostscript` can do that as well was using `Ghostscript` for other optimizations, but how does it behave in case of transparent images etc. 

I agree `\<object\>  or \<embed\> comes with an overhead but in my case i had to embed svg, as single file was the requirement.

**Comment by duanyao** [comment]
>how does it behave in case of transparent images etc

Converted to soft marked images.

>i had to embed svg, as single file 

I see, in this case `<object>` or `<embed>` must be used. Do your pdfs contain many drawings? If not, png background can also be used.

**Comment by bilalmughal** [comment]
> Do your pdfs contain many drawings?

In some cases it can containg lots of drawings. So for now i am stuck with `\<object\>`.

**Comment by duanyao** [comment]
Because https://bugs.webkit.org/show_bug.cgi?id=99677 has been fixed for a while, close this bug.
