### ISSUE TITLE
Integration in webpage

### ISSUE THREAD

**Issue by krambiorix** [coolwanglu/pdf2htmlEX#465]
Hi, 

first of all i'd like to say: great application!

Is it possible to integrate the resulting html content in a webpage?

I tried removing html, head and body tag in the manifest file but my content is not displayed as it should be: all margins are there like in the pdf file and the content is moved to the right even if i don't have the sidepanel.

Any ideas on how to do this?

Thanks in advance!

**Comment by krambiorix** [comment]
bump

**Comment by coolwanglu** [comment]
It is possible to do that, but you might want to understand the css rules defined by pdf2htmlEX in order to hack them.

**Comment by krambiorix** [comment]
any ideas what to change? 
I see in the generated code for example: <div class="pd w0 h0" style="height: 1500px;">

-> how can i change this height to auto?

**Comment by walidsa3d** [comment]
I want to integrate the output in a webpage too

**Comment by coolwanglu** [comment]
It seems that you need to hack the source code of pdf2htmlEX, or write an (external) post-processor for your task. Unfortunately it is not supported by pdf2htmlEX now. There are use cases integrating pdf2htmlEX's output in their web pages, and you might want to figure out how they did that.
