### ISSUE TITLE
Embed only the glyphs the document is using

### ISSUE THREAD

**Issue by Helidium** [coolwanglu/pdf2htmlEX#468]
Is it possible, to generate font files using only the glyphs that are used in the document. That way file size would be reduced significantly. Is something similar already supported in pdf2htmlEX?

**Comment by coolwanglu** [comment]
There used to be such a feature, but removed, as it didn't work well.
But anyway this is kind of a 'PDF optimization' feature, which is not likely to be included in pdf2htmlEX in the future.
