### ISSUE TITLE
pdf2htmlex 0.11 (43e3174cbc) : build fails using poppler 0.31.0, cannot initialize a parameter of type 'PSOutputDev *' with an rvalue of type 'bool'

### ISSUE THREAD

**Issue by dbevans** [coolwanglu/pdf2htmlEX#471]
Mac OS X 10.9.5 (Mavericks)
MacPorts 2.3.3
Xcode 6.1.1

Build fails as follows

[ 16%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o
/usr/bin/clang++    -pipe -Os -arch x86_64 -stdlib=libc++  -Wall -stdlib=libc++ -std=c++0x -O2 -DNDEBUG -arch x86_64 -mmacosx-version-min=10.9 -I/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src -I/opt/local/include/poppler -I/opt/local/include/fontforge -I/opt/local/include    -o CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o -c /opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/font.cc
In file included from /opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/font.cc:21:
In file included from /opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/HTMLRenderer.h:27:
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/StringFormatter.h:37:12: warning: class 'GuardedPointer' was previously declared as a struct [-Wmismatched-tags]
    friend class GuardedPointer;
           ^
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/StringFormatter.h:19:12: note: previous use is here
    struct GuardedPointer
           ^
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/StringFormatter.h:37:12: note: did you mean struct here?
    friend class GuardedPointer;
           ^~~~~
           struct
In file included from /opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/font.cc:21:
In file included from /opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/HTMLRenderer.h:33:
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/BackgroundRenderer/BackgroundRenderer.h:18:1: warning: class 'Param' was previously declared as a struct [-Wmismatched-tags]
class Param;
^
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/Param.h:16:8: note: previous use is here
struct Param
       ^
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/BackgroundRenderer/BackgroundRenderer.h:18:1: note: did you mean struct here?
class Param;
^~~~~
struct
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/font.cc:890:49: error: cannot initialize a parameter of type 'PSOutputDev *' with an rvalue of type 'bool'
    if(auto * font_loc = font->locateFont(xref, gFalse))
                                                ^~~~~~
/opt/local/include/poppler/goo/gtypes.h:36:16: note: expanded from macro 'gFalse'
#define gFalse false
               ^~~~~
/opt/local/include/poppler/GfxFont.h:243:51: note: passing argument to parameter 'ps' here
  GfxFontLoc *locateFont(XRef *xref, PSOutputDev *ps);
                                                  ^
/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc/src/HTMLRenderer/font.cc:945:56: error: cannot initialize a parameter of type 'PSOutputDev *' with an rvalue of type 'bool'
    GfxFontLoc * localfontloc = font->locateFont(xref, gFalse);
                                                       ^~~~~~
/opt/local/include/poppler/goo/gtypes.h:36:16: note: expanded from macro 'gFalse'
#define gFalse false
               ^~~~~
/opt/local/include/poppler/GfxFont.h:243:51: note: passing argument to parameter 'ps' here
  GfxFontLoc *locateFont(XRef *xref, PSOutputDev *ps);
                                                  ^
2 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_macports_trunk_dports_textproc_pdf2htmlex/pdf2htmlex/work/pdf2htmlEX-43e3174cbc'

See https://trac.macports.org/ticket/46790

**Comment by dbevans** [comment]
It appears that the problem is with API changes introduced in poppler 0.31.0 in the following two commits

http://cgit.freedesktop.org/poppler/poppler/commit/poppler/GfxFont.cc?id=30a0baa353c374165e5f411efc4203746f14a74d

http://cgit.freedesktop.org/poppler/poppler/commit/poppler/SplashOutputDev.cc?id=6b072500b5ac936631be6b29b7d5a591848a18f3

For patch that fixes the problem for MacPorts see

https://trac.macports.org/changeset/132692

**Comment by coolwanglu** [comment]
Right, could be harder than I expected. I'll take a look.

**Comment by coolwanglu** [comment]
Fixed in the incoming branch. Thanks!
