### ISSUE TITLE
What version and invocation are you using for the Mediafire pdf2htmlEX preview?

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#473]
Have some incompatibilities, getting ugly output by default on some PDFs with the following settings:

pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.24.5
  libfontforge 20141104
  cairo 1.13.1
Default data-dir: /usr/share/pdf2htmlEX
Supported image format: png jpg svg

**Comment by coolwanglu** [comment]
I have no idea. You should probably ask Mediafire.

**Comment by Toneti777** [comment]
@djvs Do you have a answer? I get diferent results too.
Thanks.

**Comment by djvs** [comment]
I didn't ask them.

coolwanglu: Having the following output problems 
![2015-02-17-112011_541x447_scrot](https://cloud.githubusercontent.com/assets/2954343/6231960/fe32a564-b696-11e4-94eb-d362f0e5e612.png)

**Comment by Toneti777** [comment]
I asked to MediaFire...
This is the answer...

![a](https://cloud.githubusercontent.com/assets/1532243/6345274/6a5b2316-bc04-11e4-8453-7fc1b07b5952.png)

**Comment by Toneti777** [comment]
This page have a font error...can you gave me any idea?
https://www.dropbox.com/s/157yu1v5m74qrrf/infali.pdf?dl=0
Thanks.
