### ISSUE TITLE
Not able to convert pdf

### ISSUE THREAD

**Issue by truptipawar-wits** [coolwanglu/pdf2htmlEX#474]
I'm trying to convert this PDF. 
It creates internal page files but does not create the main container html file.
Also I'm getting error as,
 'ToUnicode CMap is not valid and got dropped for font: 1 Cannot flatten a non-CID font'

Here is the link for PDF: https://dl.dropboxusercontent.com/u/44823637/pdf2htmlex_test/test.pdf

Thank you for any help!

**Comment by Sequa** [comment]
The error message seems to be the same as in this issue: https://github.com/coolwanglu/pdf2htmlEX/issues/455
I would really appreciate if someone could look into this. Thanks!

**Comment by coolwanglu** [comment]
Just fixed in `incoming`.
