### ISSUE TITLE
is it possible to split pages on stand alone html files?

### ISSUE THREAD

**Issue by ricardodelagarza** [coolwanglu/pdf2htmlEX#476]
The code works pretty well to resemble PDF format on html. Specially in PDF with complex design layout.

The option to split pages does separate html files, but in fact they only had the div with the page content. 
The question is How can I convert one multiple pages PDF to multiple totally independent .html sharing the fonts and CSS

**Comment by coolwanglu** [comment]
This is not yet supported. You can convert single pages, but the resource files are not shared that way.
