### ISSUE TITLE
Output messed

### ISSUE THREAD

**Issue by hermesramos** [coolwanglu/pdf2htmlEX#479]
When I use pd2htmlEX ppa, I get an output messed. When I conver the same file on mediafire.com, I get a perfect output. Would be possible to update the ppa, please?

http://www.mediafire.com/view/zx3eakj1tfnqd8a/INPDFViewer.pdf

THANKS

**Comment by coolwanglu** [comment]
PPA is usually the stable version, which may not include the latest commits.
Have you tried the latest git version?

**Comment by brunon81** [comment]
I tried the latest git version pdf2htmlEX with both the fontforge's git version and the pdf2htmlEX's fontforge version.

The fonts are still no good.

Can you trying converting to html to see the output am I am talking about, please?

Thank you very much in advance

**Comment by hermesramos** [comment]
I tried the latest git version pdf2htmlEX with both the fontforge's git version and the pdf2htmlEX's fontforge version.

The fonts are still no good.

Can you trying converting to html to see the output am I am talking about, please?

Thank you very much in advance

**Comment by duanyao** [comment]
@hermesramos can you upload your pdf here so I can have a look?
https://bitbucket.org/duanyao/pdf2htmlex/issues

Because many foreign web storage services are not usable in China.

**Comment by hermesramos** [comment]
Done!

Issue #4.

Thanks!!

**Comment by duanyao** [comment]
@hermesramos you uploaded a html file.

**Comment by hermesramos** [comment]
I am so sorry. I re upload. I could add it issue #4, since I created it anonymous. It is now in the issue #5.

Please, close issue #4

**Comment by duanyao** [comment]
I can convert the file perfectly with pdf2htmlEX, version 568dc8e65029097cae1aef84d902f5e1c311c35b of incoming branch.

fontforge 's git version is 5f85fd7be65a0a198cd97376e79136e6482deb57

poppler version is bc8076d8f638ccb44f8e3b94aaae96850b025deb

**Comment by hermesramos** [comment]
I will test the incoming branch and let you know. Thanks

**Comment by hermesramos** [comment]
Hi! I just compiled with the versions above, but no luck. The font are still strange.

I get the same font output when using pdf2htmlEX windows.

I am using ubuntu with the same hash version as above.

Any ideias?

Here is the attached image:

![1](https://cloud.githubusercontent.com/assets/11175800/6709451/32179326-cd58-11e4-9e08-1f57c8a94fb3.png)

**Comment by coolwanglu** [comment]
It looks like something wrong in fontforge to me.

**Comment by hermesramos** [comment]
Yes. Me too. 

You will get the same output from:
1. Ubuntu's trusty pdf2htmlEX ppa;
2. Ubuntu viid apt-get pdf2htmlEX;
3. Windows pdf2htmlEX port;
4. Also using the same hash version as above.

Any ideas? Can you help me, please?

**Comment by coolwanglu** [comment]
I cannot reproduce it on Mac, with Chrome or Firefox.

**Comment by hermesramos** [comment]
Do you have windows or ubuntu?

**Comment by coolwanglu** [comment]
Sorry I didn't write it clearly. I converted the files in Linux, and viewed the output on Mac. I've got only a headless linux.

**Comment by hermesramos** [comment]
:/ I am lost. Any ideas? I am getting the same output over and over, not matter what version I install

**Comment by duanyao** [comment]
What browser you used? I've expericenced that firefox sometimes fails to load web fonts, restart firefox or rename the html file may help. If the problem persists, please upload the converted html.

**Comment by hermesramos** [comment]
Thanks for the quick answer.

I have tried Chrome, FireFox and IE. No luck. Just tried renaming and restarting.

Here is the html.

https://drive.google.com/file/d/0BxpKnjz03VANSlRjV0ZZQ1NaVVE/view?usp=sharing

If you need me to upload it to a different location, please, let me know.

**Comment by duanyao** [comment]
Please upload to bitbucket.

**Comment by hermesramos** [comment]
Attached!

https://bitbucket.org/duanyao/pdf2htmlex/issue/5/output-messed-479#comment-16565543

**Comment by duanyao** [comment]
Some fonts in the converted html are weired, some glyphs are stretched about 1 time taller. If your fontforge has same version as mine, I would guess some dependencies of fontforge caused the problem. Can you post the result of `configure` when you built your fontforge?

**Comment by duanyao** [comment]
Some stretched fonts (JAGEOG+Arial-BoldItalicMT, JAGEOF+Arial-ItalicMT) in hermesramos's output have em size 1000 but same fonts in my output have em size 2048. @coolwanglu Do you have any idea why the em sizes differs?

**Comment by coolwanglu** [comment]
@duanyao Looks like #87, which I did not find a solution for.

**Comment by hermesramos** [comment]
HI! I attached my fontforge configuration to bitbucked

Thanks

**Comment by hermesramos** [comment]
If you guys want, I can install logmein to my linux. I think it may help!

Thanks

**Comment by coolwanglu** [comment]
@hermesramos One way of solve this kind of issue, is for you to set up a VM, installing a minimal Linux, and try to reproduce it. If you can, then I can receive the VM image and continue working on it. Otherwise you may try to find the difference between the VM and your problematic environment.

**Comment by duanyao** [comment]
@coolwanglu Yes, looks very much like #87 .

@hermesramos Your fontforge has less optional libraries than mine.
Yours:
```
  cairo			check	yes	http://www.cairographics.org/
  giflib		check	no	http://giflib.sourceforge.net/
  libjpeg		check	no	http://en.wikipedia.org/wiki/Libjpeg
  libpng		check	yes	http://www.libpng.org/
  libreadline		check	no	http://www.gnu.org/software/readline
  libspiro		check	no	https://github.com/fontforge/libspiro
  libtiff		check	no	http://en.wikipedia.org/wiki/Libtiff
  libuninameslist	check	no	https://github.com/fontforge/libuninameslist
  zeromq (libzmq)		no	http://www.zeromq.org/
  X Window System		yes
```
Mine:
```
  cairo			check	yes	http://www.cairographics.org/
  giflib		check	yes	http://giflib.sourceforge.net/
  libjpeg		check	yes	http://en.wikipedia.org/wiki/Libjpeg
  libpng		check	yes	http://www.libpng.org/
  libreadline		check	yes	http://www.gnu.org/software/readline
  libspiro		check	yes	https://github.com/fontforge/libspiro
  libtiff		check	yes	http://en.wikipedia.org/wiki/Libtiff
  libuninameslist	check	yes	https://github.com/fontforge/libuninameslist
  zeromq (libzmq)		no	http://www.zeromq.org/
  X Window System		yes
```
I built it like this:
```
sudo apt-get install autotools-dev libjpeg-dev libtiff4-dev libpng12-dev libgif-dev libxt-dev autoconf automake libtool bzip2 libxml2-dev libuninameslist-dev libspiro-dev python3-dev libpango1.0-dev libcairo2-dev chrpath uuid-dev python-dev

./bootstrap
./configure --enable-debug
make
sudo make install
```

Before you rebuild your fontforge, can you test it as follow?

1. open your PDF with fontforge (by GUI or command line `INPDFViewer.pdf`)
2. select font "JAGEOG+Arial-BoldItalicMT"
3. open menu "Element->Font Info->General".

What's the "Em size"? it should be 2048.

**Comment by hermesramos** [comment]
It says 2048, just like you said!

**Comment by hermesramos** [comment]
I will upload a virtual machine. Do you guys have access to google drive, mega, dropbox?

**Comment by coolwanglu** [comment]
@hermesramos Since it says 2048, the VM will be no use to us. It shows that pdf2htmlEX would work in that VM (is the output of pdf2htmlEX in the VM correct?). In this case, you need to compare and find the cause. Well I'm thinking roughly the same as @duanyao, probably something wrong with your build of fontforge, could be old dependencies.

**Comment by coolwanglu** [comment]
@hermesramos Oh I could be wrong. When you meant 2048, is that in the original environment, or the new VM?

**Comment by hermesramos** [comment]
It is the same VM, I am doing the tests in one. The output is still not right :/. I have tried pdf2htmlEX in many vms, including using the windows port, all have the same issue with the font.

I tried using from the ppa with a fresh install, same issue.

I am lost :/

**Comment by duanyao** [comment]
So it seems your fontforge can parse the font correctly. Then you can try to convert "JAGEOG+Arial-BoldItalicMT" etc. to woff format by fontforge, and check whether the EM sizes are changed or glyphs are stretched.

**Comment by hermesramos** [comment]
I did the exporting to woff. The output is still 2048 EM. 

I created the VM myselfd. I didnt know theres prepared VM existed. I am downloading right know and let you know.

Thanks you all very much so far

**Comment by duanyao** [comment]
If the problem persists, please upload your VM to MEGA (I can't access google drive or dropbox).

**Comment by hermesramos** [comment]
Wow!!! Just wow!!!!!

I downloaded the VM from osboxes.org. Instaled pdf2htmlex from apt-get. BAM! It worked. Simple like that.

Thank you all very much!!!!!!!!
