### ISSUE TITLE
Hidden content shown 

### ISSUE THREAD

**Issue by sathishks** [coolwanglu/pdf2htmlEX#480]
Hi ,
pdf2htmlEX --split-pages 1 --fit-width 800 2_RogueTrader.pdf

Below pdf file is convert successfully, but some hidden content shown.

Orginal PDF : https://www.dropbox.com/s/d25j0aqqou31yar/orginal.pdf?dl=0

![orginal pdf](https://cloud.githubusercontent.com/assets/6150047/6526378/27ef109c-c437-11e4-9389-e7c15b50d115.png)

Converted HTML:

![converted html](https://cloud.githubusercontent.com/assets/6150047/6526388/3e35d624-c437-11e4-9f3f-2d81dda21816.png)

version info:

pdf2htmlEX -v
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributers
Libraries:
poppler 0.25.0
libfontforge 20140221
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

Thanks,

Sathish Kumar S

**Comment by coolwanglu** [comment]
Did it work with text visibility option?

**Comment by sathishks** [comment]
@coolwanglu  : I am using this --correct-text-visibility 1 option but below error shown.

"pdf2htmlEX: unrecognized option '--correct-text-visibility'"

**Comment by sathishks** [comment]
@coolwanglu : please advise on this
I am using this option --correct-text-visibility 1 but below error shown.

"pdf2htmlEX: unrecognized option '--correct-text-visibility'"

**Comment by coolwanglu** [comment]
@sathishks It seems that the version you are using is too old. Are you using the 0.12 release, or any (git) version before the release.
Anyways, I'd recommend updating to the latest git version.

**Comment by sathishks** [comment]
@coolwanglu : I am already using latest version.

version info:

pdf2htmlEX -v
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributers
Libraries:
poppler 0.25.0
libfontforge 20140221
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

**Comment by coolwanglu** [comment]
The latest version is 0.13
https://github.com/coolwanglu/pdf2htmlEX/blob/incoming/CMakeLists.txt#L12

Maybe you are not using the incoming branch?

**Comment by coolwanglu** [comment]
Micro version number will be introduced to mark the git commits more precisely. Hopefully it will be useful.

**Comment by coolwanglu** [comment]
I opened the file with Adobe Reader, and the content turn out to be visible.
