### ISSUE TITLE
After the PDF conversion, Document content shown as empty

### ISSUE THREAD

**Issue by sathishks** [coolwanglu/pdf2htmlEX#482]
Hi,
pdf2htmlEX --split-pages 1 --zoom 3 --fit-width 920 present.pdf

After the PDF conversion, Document content shown as empty,please advise on this.

Note: check the below file and attachment.

Orginal PDF :

https://www.dropbox.com/s/h3f0seswyg9mj1h/present.pdf?dl=0

After Conversion:

![screen shot 2015-03-11 at 9 38 59 am](https://cloud.githubusercontent.com/assets/6150047/6590195/7d0cdb7e-c7d2-11e4-9382-6de25a6ca732.png)

version info:

pdf2htmlEX -v
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributers
Libraries:
poppler 0.25.0
libfontforge 20140221
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg

Thanks,
Sathish Kumar S

**Comment by sathishks** [comment]
@coolwanglu : Any update on this.

**Comment by coolwanglu** [comment]
I cannot reproduce it. Please try the latest `incoming` branch. (and reopen if necessary)
