### ISSUE TITLE
The PostScript font name "XXXXX" is invalid. It should be printable ASCII,

### ISSUE THREAD

**Issue by khiav223577** [coolwanglu/pdf2htmlEX#486]
我在轉換pdf檔時，有些字型無法成功轉換，不知道是什麼問題？
PDF檔：http://www.csie.ntu.edu.tw/~b99902030/pdf2htmlex/1CH0311359.pdf
轉換結果：http://www.csie.ntu.edu.tw/~b99902030/pdf2htmlex/1CH0311359.html
（補充）：後來發現只有mac上的chrome顯示不正常...以下是我看到的畫面
http://www.csie.ntu.edu.tw/~b99902030/pdf2htmlex/1CH0311359.png
－－－－－－－－－－－－－－－－
我是透過brew install pdf2htmlex安裝的。
OS X 10.9.5
pdf2htmlEX version 0.12
Libraries: 
  poppler 0.29.0
  libfontforge 20141227

![1](https://cloud.githubusercontent.com/assets/4011729/6682413/7a0de248-ccb3-11e4-91f5-50a831a419b2.png)

**Comment by coolwanglu** [comment]
我测试了一下，字体名如果含有非法字符，浏览器可能会拒绝加载字体。
刚刚在incoming分支修正了。
