### ISSUE TITLE
version 0.12 build failed with gcc 4.9.2

### ISSUE THREAD

**Issue by microcai** [coolwanglu/pdf2htmlEX#492]
pdf2htmlEX-0.12/src/BackgroundRenderer/SplashBackgroundRenderer.cc:35:23: 错误：对‘SplashOutputDev::SplashOutputDev(SplashColorMode, int, bool, SplashColorPtr, bool, bool)’的调用没有匹配的函数

**Comment by hermesramos** [comment]
Use the incoming branch. I had the same problem as you.

**Comment by coolwanglu** [comment]
Should have been fixed.
