### ISSUE TITLE
Question about DrawTracer

### ISSUE THREAD

**Issue by coolwanglu** [coolwanglu/pdf2htmlEX#494]
https://github.com/coolwanglu/pdf2htmlEX/blob/incoming/src/DrawingTracer.cc#L83
@duanyao 

`cairo_transform` seems to apply the new matrix on top of existing matrix, http://cairographics.org/manual/cairo-Transformations.html#cairo-transform

But did `DrawingTracer::update_ctm` mean to set the new matrix for cairo?

**Comment by duanyao** [comment]
`DrawingTracer::update_ctm` traces `OutputDev::updateCTM`, and `OutputDev::updateCTM` provides us with the update to the CTM (which should be muliplied with CTM), not the updated CTM. This behavior seems not stated in poppler's document, but you can see `CairoOutputDev::updateCTM`, it is almost the same as `DrawingTracer::update_ctm`.

**Comment by coolwanglu** [comment]
Thanks.
