### ISSUE TITLE
请教下option配置哪一项才能使转换出来的html里包含原pdf里的所有文本

### ISSUE THREAD

**Issue by leqoqo** [coolwanglu/pdf2htmlEX#499]
我的pdf链接是：http://pan.baidu.com/s/1jG25OfO
pdf是通过wkhtmltopdf转换的

![pdf](https://cloud.githubusercontent.com/assets/8799669/6912999/3e0a3aa4-d7ac-11e4-94f3-164600693dbb.png)

转换后的html链接是：http://pan.baidu.com/s/1eQdB394
![html](https://cloud.githubusercontent.com/assets/8799669/6913002/45c2002e-d7ac-11e4-94bb-7d53cc9b0cb1.png)

我试了大部分的选项都没有成功，请教下我该如何设置option，我用的是“pdf2htmlEX-0.12-win32-static-with-poppler-data”

![shuoming](https://cloud.githubusercontent.com/assets/8799669/6913072/71f709f4-d7ad-11e4-9dbb-c3db4d5815fd.png)

**Comment by duanyao** [comment]
你的转换结果（ http://pan.baidu.com/s/1eQdB394 ）已经包含了原 pdf 里的文本。我猜你的意思是文本无法被选中和复制？这是因为大本分文本被上层的链接（`<a>`）和裁剪区（`div.c`）挡住了。

pdf的链接里并不包括文本，这是pdf的局限性，也被带到了转换后的html中。我能想到的解决方法是（1）用js来取代`<a>`的功能，但代价是在js不能用的情况下链接就失效了)；（2）把链接加入到相关的文本（`div.t`）内部，不过这么做比较复杂。

至于裁剪区（`div.c`），我已经在 #423 建议取消。

**Comment by leqoqo** [comment]
@duanyao  谢谢你的回答，我对pdf的格式了解并不多，我是为了实现我需要的网页快照功能，我的转换结果里是包含了文本，我想要的是所有的pdf中包含的所有文本转换到html后仍然是以文本格式展现，我试用了在线文档转换服务：http://www.pdftohtml.net能把所有文本都转换出来，最终展现的html没有pdf2htmlEX好。

**Comment by duanyao** [comment]
我不明白你的意思。你是想说转换后的文本结构不够好？具体是哪里不满意？
另外为什么网页快照功能需要经过PDF这个中间步骤？

**Comment by leqoqo** [comment]
@duanyao 就是既可以抽取pdf中包含的所有文本，又有一个非常好的样式，我是为了实现这个。

网页快照是我自己的叫法，我用wget 下载一个网页，网页包含了img，内嵌css，js，外部css，外联css，我要把css全部转换为内嵌css，js移除，img转换为base64，并且下载的html引用文件还不一定完整，我发现使用wkhtmltopdf把url转换pdf满足了我的需求，但最终我是用浏览器来展示该pdf，所以我又把pdf转换为了html，我使用pdf2htmlEX就是为了干这个。haha

**Comment by duanyao** [comment]
"有一个非常好的样式"——“好”的具体含义是什么？尽可能接近原来的html吗？由于html->pdf->html的转换，必然会丢失很多信息，所以是很难还原原来的html的。

你的网页快照程序需要把网页引用的资源转换为内嵌形式，有个 chrome 扩展就是做类似的事情的（ https://github.com/gildas-lormeau/SingleFile ），不过这不是命令行程序，你需要自己实现了。

**Comment by leqoqo** [comment]
你好，谢谢你的指导，我试用了chrome的pageArchiver插件，pageArchiver的核心是singleFile，
下面是两个保存html区别。
![1](https://cloud.githubusercontent.com/assets/8799669/6937053/008691a2-d88b-11e4-8e45-a5a67a989bdc.png)
pdf2htmlEX生成的html里主要包含了div，a，img，span这几个html元素，class，style 属性；比较有规则；
singlefile生成的html里包含了原有网页的所有html属性。
我有一个需求是要把我所谓的网页快照发送到邮箱里，下图是通过程序使css转换为内嵌css，下面是发送到邮箱，在邮箱里查看的效果：
![2](https://cloud.githubusercontent.com/assets/8799669/6937059/0f045caa-d88b-11e4-8536-9012223079c3.png)



![3](https://cloud.githubusercontent.com/assets/8799669/6937064/181802ba-d88b-11e4-8fc5-c4c8fa48b30c.png)



![4](https://cloud.githubusercontent.com/assets/8799669/6937071/1c9a1a26-d88b-11e4-812d-d1c80d8b220a.png)

由于email对html的支持问题，所以比较需要有规则的html，pdf2htmlex的效果很好，正在实现html中div转换为table的工作

**Comment by duanyao** [comment]
不同的邮件客户端或者 webmail 对 html 的支持/限制可能有所不同，所以指望复杂的 html 邮件在各种条件下都正常显示恐怕是有困难的。我看到你的截图中 pdf2htmlEX 的输出在email中也有很多显示错误，为什么你说“效果很好”呢？

“支持在邮件客户端中显示”恐怕已经超出了 pdf2htmlEX 和 singleFile 的目标范围了。我认为变通的办法是：把你的网页快照作为附件发送，或者发送到网页快照的链接，让用户用浏览器打开网页快照。
