### ISSUE TITLE
Trying to convert a file without .pdf file ending causes unexpected error on linux

### ISSUE THREAD

**Issue by siyb** [coolwanglu/pdf2htmlEX#501]
pdf2htmlEX --dest-dir out --split-pages 1 --printing 1 --embed-css 0 --embed-font 0 --embed-image 0 --embed-javascript 0 --embed-outline 0 --page-filename %d.page --bg-format jpg /home/user/somedir/eb8bf01a-c133-4fcb-b24d-eef1e56af85d

Error: Cannot open out/ for writing

while running

pdf2htmlEX --dest-dir out --split-pages 1 --printing 1 --embed-css 0 --embed-font 0 --embed-image 0 --embed-javascript 0 --embed-outline 0 --page-filename %d.page --bg-format jpg /home/user/somedir/eb8bf01a-c133-4fcb-b24d-eef1e56af85d.pdf

works

**Comment by coolwanglu** [comment]
Fixed in incoming.

**Comment by esoftcard** [comment]
why --splitpage not work, document display not as origianl
