### ISSUE TITLE
Relaxation of formatting?

### ISSUE THREAD

**Issue by peasthope** [coolwanglu/pdf2htmlEX#502]
Thanks for the fine software.  A great contribution to the computing community.

A PDF document is formatted for paper and is intrinsically a fixed format.  A principle of HTML is to allow the browser as much freedom as possible to accomodate local constraints.  Text which is not preformatted is wrapped to the width of the browser window.  This accomodates a narrow window on a smartphone and a wide window on a desktop system.  In both contexts text can be read without scrolling sideways.

I wonder whether a mode to relax formatting might be introduced in pdf2htmlEX.  The option could be --relaxformat <0|1>.  The extant functionality is --relaxformat 0.  With --relaxformat 1, format of headings and lists would be preserved but format of plain text would be determined by the browser.

Thanks for reading my suggestion and 

Best Regards,                ... Peter E.

**Comment by coolwanglu** [comment]
There were old issues about this, see #56 
Currently there's no plan to support reflowable text in pdf2htmlEX, but see #418, a plan is to supported tagged PDF, which can be created using other tools.

There's also a relevant option `--optimize-text`, which is not working quite well unfortunately.
