### ISSUE TITLE
DOS path not completely supported

### ISSUE THREAD

**Issue by mirhl** [coolwanglu/pdf2htmlEX#504]
Assuming I'm running pdf2htmlEX from C:\p2h
I give 
C:\p2h\pdf2htmlex.exe "document 2.pdf"

The program will throw an error saying 
Error: Cannot open ./C:\p2h\document 2.html for writing

**Comment by vinbalraj** [comment]
Check the arguments, output file name is missing
Usage: pdf2htmlEX [options] <input.pdf> [<output.html>]

Change to:
C:\p2h\pdf2htmlex.exe "document 2.pdf" "output.html"

**Comment by mirhl** [comment]
Ok my fault. 
*""* is already enough. 

It's just weird that if there are no spaces in file name, the program does not expect output file

**Comment by coolwanglu** [comment]
It seems to be a bug, as the output filename is optional.
But I cannot reproduce it.

**Comment by mirhl** [comment]
Ehrm.. windows 7 with [these binaries](http://soft.rubypdf.com/software/pdf2htmlex-windows-version) (which are quite old to be fair)

**Comment by witwall** [comment]
@mirhl pdf2htmlEX 0.13.6 windows version is out now.

**Comment by mirhl** [comment]
Fixed indeed. Thanks
