### ISSUE TITLE
fit_width() and fit_height() don't work well when called many times

### ISSUE THREAD

**Issue by davidwtf** [coolwanglu/pdf2htmlEX#506]
**fit_width()** and **fit_height()** in the pdf2htmlEX.js can't work well when I call them again.
The pages scaled in wrong ratio. You can try it.

These two functions called **rescale()** to finish the real scaling job.
I think it should pass **true** to rescale() as **the 2nd param**.
Because the 1st param (the ratio) is computed by the page's client width.
In another word, **this computed ratio is actually a relative ratio**.

And It seems work well in my project that change rescale()'s  2nd param from "false" to "true".

**Comment by coolwanglu** [comment]
Fixed in `incoming`. Thanks~
