### ISSUE TITLE
Seemingly random margins destroy 5-10% of documents

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#507]
Another sample document:

http://s3-us-west-2.amazonaws.com/oa2/docfiles/6e4b00a2-e292-4504-88b6-d4f9c895d446/6e4b00a2-e292-4504-88b6-d4f9c895d446.pdf

Compare rendered output:

http://www.openassembly.com/document/f0b8d711-2cf5-4eed-92e4-9705d46344fc?context=course-68cb65d4-b4ce-407f-97f0-84cc6dde401b

Classes _3, _4, _8 all seem to be breaking the output with unnecessary or incorrect margin-left values.  I am begging you to fix this...

**Comment by djvs** [comment]
@coolwanglu :'(

**Comment by djvs** [comment]
class WhitespaceManager : public StateManager<double, WhitespaceManager>
      {
      public:
          static const char * get_css_class_name (void) { return CSS::WHITESPACE_CN; }
          double default_value(void) { return 0; }
          void dump_value(std::ostream & out, double value) { 
              out << ((value > 0) ? "display:inline-block;width:" 
                                  : "display:inline;margin-left:")
                  << round(value) << "px;";
          }
          void dump_print_value(std::ostream & out, double value, double scale) 
          {
              value *= scale;
              out << ((value > 0) ? "display:inline-block;width:" 
                                  : "display:inline;margin-left:")
                  << round(value) << "pt;";
          }
      };

**Comment by djvs** [comment]
The values being fed to one of these are wrong.   Specifically in the case where value < 0.

**Comment by duanyao** [comment]
Seems you are using an old version. Latest codes in incoming branch converts your file correctly.

**Comment by djvs** [comment]
I just pulled from master, compiled and tested it on one of these problem PDFs. It is far from correct.  Interestingly, removing the margin-left parts from the above code (and adjusting accordingly) seems to fix these problems entirely, am going to test it on a more sophisticated file now.

**Comment by djvs** [comment]
Yes, output is still perfect AFAICT with the "issue65_en" sample file given on main github page.  It appears to be the case that all `margin-left:` (negative); values are somehow erroneous.  Sending a PR.

**Comment by djvs** [comment]
@duanyao  What is your output for `pdf2htmlex --version`?

**Comment by djvs** [comment]
Excuse last messages - yes, thank you, looks good.
