### ISSUE TITLE
compressing the output html file

### ISSUE THREAD

**Issue by hdave30** [coolwanglu/pdf2htmlEX#508]
i want the output file being created to be compressed. For files with more number of images, the output html file is very large. I want the created file to be compressed and do not want to separately read the html output file again and compress it.. Is there a way I can achieve it ?

Thanks.

**Comment by hojuruku** [comment]
The whole point here is that it is mean't to be uncompressed. It's html5. You don't want to decompress in a web-browser's page rendering engine. That would require JavaScript or something like that like the evil pdf.js from Mozilla uses.

Embedding as base64 should be avoided, if your setup allows for it.

Web browsers support different compressed streams, and if you are putting the PDF files in the cloud (azure amazon s3 etc) you must pre-compress the data, or you can compress on the fly with mod_deflate on an apache webserver for example. You could probably pre-compress the content using extra Apache-config or have your app add the appropriate html headers. The decompression is done in the web browser not in javascript. And you can pre-compress the content. You may also need uncompressed content for weird web-browsers that don't support compression.

http://httpd.apache.org/docs/2.2/mod/mod_mime.html#addencoding & MultiViews 
Choose any compression supported by the client web-browsers 
http://httpd.apache.org/docs/2.2/content-negotiation.html

Personally I think this bug report is a misnomer. The image files used by pdfhtml2EX should be compressed, if not you can compress them again even better afterwards with a numerous collection of image manipulations tools.

https://developers.google.com/speed/pagespeed/module/filter-image-optimize
Google pagespeed also does this.

http://en.wikipedia.org/wiki/Zopfli
Best deflate compressor.

http://www.whatsmyip.org/http-compression-test/
See if your bowser is requesting compressed content.

**Comment by coolwanglu** [comment]
@hojuruku  Right. Thanks for the explanation.
