### ISSUE TITLE
letter-spacing and word-spacing instead of _n spans

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#510]
Seems like file size and DOM complexity could be reduced 80-90% if this code was refactored.   If  some span is like this:

    <span class="whatever">
      <span class="_ _1">W<span>
      <span class="_ _1">h<span>
      <span class="_ _1">y<span>
      <span class="_ _2"> <span>
      <span class="_ _1">t<span>
      <span class="_ _1">h<span>
      <span class="_ _1">e<span>
      <span class="_ _2"> <span>
      <span class="_ _1">m<span>
      <span class="_ _1">a<span>
      <span class="_ _1">r<span>
      <span class="_ _1">g<span>
      <span class="_ _1">i<span>
      <span class="_ _1">n<span>
      <span class="_ _1">s<span>
    </span>

with `._1{ display:inline; margin-left:-5px;}` and `._2{ width:20px;}`

then why not just:

    <span class="whatever">
      Why the margins
    </span>

with `.whatever{ letter-spacing:-5px; word-spacing:20px;}` ?

Just a suggestion.

**Comment by duanyao** [comment]
Try `--optimize-text 1`, this option is supposed to convert offsets to `letter-spacing/word-spacing`.

**Comment by djvs** [comment]
Nice!  Thanks.
