### ISSUE TITLE
cmake doesn't work

### ISSUE THREAD

**Issue by jask05** [coolwanglu/pdf2htmlEX#512]
Hi,

I'm trying to compile pdf2htmlex into CentOS 6.6 and this is the message that I get when I use cmake:

[root@dalim pdf2htmlEX-master]# cmake .
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- checking for module 'poppler>=0.25.0'
--   package 'poppler>=0.25.0' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:22 (pkg_check_modules)

-- checking for module 'cairo>=1.10.0'
--   package 'cairo>=1.10.0' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:28 (pkg_check_modules)

Trying to locate cairo-svg...
CMake Error at CMakeLists.txt:47 (message):
  Error: no SVG support found in Cairo

-- Configuring incomplete, errors occurred!
See also "/home/seinet/Descargas/pdf2htmlEX-master/CMakeFiles/CMakeOutput.log".

---------------------

poppler: poppler-0.12.4-3.el6_0.1.x86_64 - I can't update it.
cairo: cairo-1.8.8-3.1.el6.x86_64 - I can't update it.

CMakeOutput.log -> http://pastebin.com/Khpj90JW

Can you help me?

Thanks !!

**Comment by coolwanglu** [comment]
You don't have sufficient dependencies installed.

**Comment by hudeyongs** [comment]
Same error : CMake Error at CMakeLists.txt:47 (message):
Error: no SVG support found in Cairo ,i've googled for a whole day ,help.
