### ISSUE TITLE
Cosmetic Defect: pdf2htmlEX -v complains about github master fontforge being outdated :)

### ISSUE THREAD

**Issue by hojuruku** [coolwanglu/pdf2htmlEX#513]
Libraries:
  poppler 0.26.5
  libfontforge 150430
  cairo 1.14.2
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg

Warning: pdf2htmlEX has been built with a too old version of Fontforge, which is not supported.

Not hard to fix this ;)

**Comment by coolwanglu** [comment]
Thanks!
I simply removed it, as the version of fontforge is checked in cmake.
