### ISSUE TITLE
Background image creation based on --fit-width or --fit-height

### ISSUE THREAD

**Issue by Deepanraj79** [coolwanglu/pdf2htmlEX#518]
I need to generate the background image file based on the given --fit-width or --fit-height value. Can anyone assist if there any options available to solve this?

For example: 

Command used: pdf2htmlEX --bg-format  --fit-height 500 jpg pdfname.pdf

pdf file page width: 842

pdf file page height: 631

The generated background image file in pixels : 1684 x 1263

But I should only have the background image file based on the --fit-height value. It supposed to be 667 x 500 pixels.

**Comment by coolwanglu** [comment]
You can try to tweak the dpi through parameters.
However note that the size of images may not follow these values, as the empty margins may get trimmed.
