### ISSUE TITLE
Image Sizes are not reduced with Zoom

### ISSUE THREAD

**Issue by muthugp** [coolwanglu/pdf2htmlEX#519]
My test 14MB PDF document has around 300 pages, when converted to HTML the whole size comes to 33MB. I understand PDF is compressed version and its size is smaller. Images of HTML output produced is 31MB (i use split pages and --embed fcij options).

My question is, even if i zoom option --zoom 0.5, the images sizes remain same (width, height and size). The zoom option just sets width and height in CSS for HTML Divs.
Is there anyway to reduce the file size accordance with zoom factor?

Thanks,
Muthu

**Comment by duanyao** [comment]
`--hdpi` and `--vdpi` affect size of jpg/png background images. You can also try `--bg-format svg --svg-embed-bitmap 0` to dump raw images in the PDF, this usually generate smaller output. See the man page for more info.

**Comment by muthugp** [comment]
Thanks for the info Duan. I can reduce the image sizes with --hdpi and --vdpi (low resolution for mobile\iPad). I am not sure SVG images are cached in browsers, so i go with PNG\JPG.

Still wondering it would be nice to have PDF2HTMLEx reduces\increases the images extracted from PDF in accordance with zoom factor. (When i reduce(zoom out) a PDF by 50%, why i need same size of image).

**Comment by duanyao** [comment]
I'm not sure the rationale why `--zoom` doesn't affect sizes of background images, maybe @coolwanglu can answer you. Maybe some users want high resolution background images for mobile/pad because these devices usually have high resolution screens.

**Comment by coolwanglu** [comment]
`--zoom` and `--fit-width/height` adjust the parameters of the viewer. The quality is not altered as the users may zoom in/out themselves, and we do not want to lower the quality due to a small default zoom factor.

**Comment by muthugp** [comment]
Makes sense. 
I can use --hdpi and --vdpi for smaller images. 
Thanks.
