### ISSUE TITLE
how to upgrade to the latest fontforge

### ISSUE THREAD

**Issue by leomayleomay** [coolwanglu/pdf2htmlEX#522]
I am wondering if I could upgrade fontforge to the latest for the pdf2htmlEX, I have installed the latest fontforge on my Mac, and I have no idea how to let the pdf2htmlEX pick it up.

* fontforge version
```
libfontforge 20150401
```

* pdf2htmlEX version
```
pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries:
  poppler 0.26.4
  libfontforge 20140928
```

**Comment by duanyao** [comment]
You have to rebuild pdf2htmlEX after you installed a new version of libfontforge. Or wait for a new binary release of pdf2htmlEX.
