### ISSUE TITLE
-webkit-overflow-scrolling: touch crashes browser on iPad

### ISSUE THREAD

**Issue by muthugp** [coolwanglu/pdf2htmlEX#523]
In my 200 pages converted HTML output with --split-pages option for quick loading on browser, if i add -webkit-overflow-scrolling: touch to #page-container, browser (Safari\Chrome\Dolphin) on iPad (iOS version 8.1.1) crashes. If i remove this CSS property, everything is OK except of sticky scrolling. We need this CSS property for fast scrolling. 

If i don't use --split-pages option, above CSS works perfect without crashing. But the drawback is, user has to wait a min to load the whole HTML file containing 200 pages.

If it works with HTML converters without --split-pages, why not with split pages? What is the difference in CSS between these two conversion?

Please help!

**Comment by duanyao** [comment]
Ideally a browser should never crash no matter what you feed to it; if it does, it is a bug of the browser. However, in practice complicated pages can cause a browser to run out of memory, and get killed. I don't think `--split-pages` should result in more memory usage. can you monitor the memory usage of your browsers?

`-webkit-overflow-scrolling: touch` uses more memory, and seems did cause crashes:

http://stackoverflow.com/questions/12665641/ios-browser-crashing-when-using-webkit-overflow-scrolling-touch

**Comment by coolwanglu** [comment]
I agree with @duanyao . It seems that there's few thing we can do on this side.
