### ISSUE TITLE
Produce separated HTML file for each page

### ISSUE THREAD

**Issue by xylosper** [coolwanglu/pdf2htmlEX#524]
First of all, thank you for great work.
The converted result is really beautiful but I want to make a feature request here.

As far as I can see from the option list, generating separated HTML for each page is not supported.
Although `--split-pages` can produce a main HTML and separated .page files, but each page cannot be used as stand-alone HTML file because in that case, hyperlinks pointing to separated external page won't work.

It would be nice to introduce a feature to generate separated HTML files for each single page.

**Comment by duanyao** [comment]
`-f N -l N` options can generate a standalone HTML for page N of a PDF.

You can also add necessary header/footer to each .page files generated by `--split-pages` yourself to make them complete HTML files.

**Comment by xylosper** [comment]
@duanyao It doesn't do nothing for broken links, does it?

**Comment by duanyao** [comment]
I believe .page files should contain links.

**Comment by xylosper** [comment]
Yes. It contains **BROKEN** links if the links point to anchors in other pages.

**Comment by duanyao** [comment]
Those links need some transform, because they are pointing to the ids of other pages, and they should pointing to the file names of other pages in your case. You can write a post-processing program to add header/footer to each .page files and transform links in them.

P.S. What's the benefit of separated HTML file for each page over each .page files for each page?

**Comment by xylosper** [comment]
> You can write a post-processing program to add header/footer to each .page files and transform links in them.

This phrase just makes most feature requests invalid ones.

> P.S. What's the benefit of separated HTML file for each page over each .page files for each page?

One HTML for one page makes sense if each page contains separated content.
For instance, I can make one page for each chapter and I want to make an HTML for each chapter, that is one page. Or, some PDFs of slides/poster for presentation would contains separated content for each page.
Futhermore, generally, for large PDF file with lots of pages, loading all content in one HTML file would impact bad performance.

**Comment by coolwanglu** [comment]
Maybe it's not very hard to support multi-html pages, using `iframe`'s. Yet special care must be taken to proper include necessary css files.

But over the years I don't feel that it's required by many people, nor any would be interested enough to send a patch.

**Comment by xylosper** [comment]
Fine. Thank you.
