### ISSUE TITLE
Not able to install latest version of PDF2HTMLEX in CentOS 6.4

### ISSUE THREAD

**Issue by karthiklin** [coolwanglu/pdf2htmlEX#525]
i try to install pdf2htmlEX but i faced below error in fontforge compile time

[root@xxxxxxxxxxx/tmp/code/fontforge-20150430]# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
[root@xxxxxxxxxxxxxx/tmp/code/fontforge-20150430]# ./configure "--without-libzmq" "--without-x" "--without-iconv" "--disable-python-scripting" "--disable-python-extension"
configure: WARNING: unrecognized options: --without-iconv
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... gnutar
checking whether to disable maintainer-specific portions of Makefiles... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/code/fontforge-20150430':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
[root@xxxxxxxxx/tmp/code/fontforge-20150430]#

Please help to install

**Comment by duanyao** [comment]
As the error message said, see `config.log' for more details.

If the error is only a fontforge error, maybe it is better to ask at https://github.com/fontforge/fontforge .
