### ISSUE TITLE
Help needed to understand font-family

### ISSUE THREAD

**Issue by kjayanth** [coolwanglu/pdf2htmlEX#527]
Hi,

We are using pdf2htmlex for converting pdfs to htmls to later process them. The htmls generated have fonts embedded in them in base encode URI format.  

While processing the text in the htmls it is important for us to understand the properties of text like if it is bolded/underlined etc. But what we have observed is that the font-family definition of the text doesn't convey this directly, but actually the font itself has these properties set. This is making it hard for us to achieve what we want to. 

So our question is, is there a way to figure out from the font embedded if the text associated with the font is bolded or not. And similar such properties. 

It would also be helpful to understand how the fonts are generated in the final html. 

Thanks,
Karthik

**Comment by duanyao** [comment]
>So our question is, is there a way to figure out from the font embedded if the text associated with the font is bolded or not.

This can not be done reliably, because in PDF files, texts don't have properties like "bold" or "italic", instead it relies on bold/italic fonts. So best thing you can do is check whether there are strings "bold" or "italic" in a font name (open the dumped font files by fontforge).

There is also no concept "underline" in PDF, it is just a independent line. So there is also no underlined text in pdf2htmlEX-genrated html.

**Comment by kjayanth** [comment]
Thanks for the reply. Can you point me to the dumped font files you are referring to ? I just run the following command everytime:

pdf2htmlEX <location_of_pdf> <target_location_of_html>

**Comment by kjayanth** [comment]
Also the font-names I see are ff1, ff2 etc unless I am missing something.

**Comment by duanyao** [comment]
Use `--embed-font 0` to dump font files, or font files are embedded in the HTML file. See the wiki for more info (e.g. https://github.com/coolwanglu/pdf2htmlEX/wiki/Quick-Start).

Open the font files by fontforge, open menu "element->font info->PS name", you will see the font name.

**Comment by kjayanth** [comment]
Thanks for the reply. You have answered all my questions. Closing this issue.

**Comment by coolwanglu** [comment]
Due to a recent bug, PSnames of the fonts are wiped out by pdf2htmlEX.
On the other hand, try `pdffonts`, which is a utility from poppler

**Comment by Sebastianvarv** [comment]
I am having the same trouble as the OP, I have extracted "div" container elements that contain a text line, but the font family names are only ff[some number] by the chronological order. Is it possible to determine somehow which word is in bold and which one is in italic?
