### ISSUE TITLE
CSS "display: inline-block" for the ".t span" selector mess up text positioning

### ISSUE THREAD

**Issue by nbeuchat** [coolwanglu/pdf2htmlEX#530]
Hi,

I would like to know what is the purpose of the CSS `display: inline-block` for the selector `.t span` in the base.css file.

I had to remove it in the base.min.css in order for my text to be displayed properly. Indeed, before removing it, I often had part of the text wrongly positioned and overlapping with other part of the text (both in IE and Chrome). When removing it, the text is perfectly positioned. 

##### With the `display: inline-block` line (default):
![textoverlap](https://cloud.githubusercontent.com/assets/8236283/7840954/fbd57408-0499-11e5-87a3-6df4d2655dee.PNG)

##### Without the `display: inline-block` line:
![notextoverlap](https://cloud.githubusercontent.com/assets/8236283/7840959/00f05b2e-049a-11e5-95e8-467aedc56198.PNG)

##### HTML:
Here is the html that produces the first line above "1.   Treatment of Reporting Brazilian  Financial Institutions. Each reporting"
```html
<div class="t m0 x2 h3 y12 ff4 fs2 fc0 sc0 ls0 ws0">
	1.  
	<span class="_ _b"> </span>
	<span class="ff3 ls1 ws93">T<span class="_ _0"/>reatment<span class="_ _0"/> of Rep<span class="_ _0"/>ortin<span class="_ _0"/>g 
		<span class="ls4 ws12">Brazilian</span>
	</span>
	<span class="ff3">
		<span class="_ _7"> </span>
		<span class="ls4 ws66">Financial Institut<span class="_ _1"/>ions.  
		<span class="ff4 ls1 ws93">Each Repo<span class="_ _0"/>rting </span>
		</span>
	</span>
</div>
```

Any idea why it is there in the first place? I am just worried that by removing it as I do it might create other problems somewhere else. If it has no use, then it should be a bug.

Best regards,
Nicolas

**Comment by duanyao** [comment]
This is a bug of chrome/webkit, and has been workarounded by https://github.com/coolwanglu/pdf2htmlEX/pull/484/ . You need to update to the leatest release.
