### ISSUE TITLE
Internal Error: Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful.

### ISSUE THREAD

**Issue by JensHH** [coolwanglu/pdf2htmlEX#531]
I have just downloaded the Windows Version from http://soft.rubypdf.com/software/pdf2htmlex-windows-verion. When I try the examples provided with the download with 
pdf2htmlEX --zoom 1.3 test/test_data/3-pages.pdf --debug 1
I get the error:
Internal Error: Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful.

Debug is:
temporary dir: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884
Preprocessing: 3/3
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__css
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__outline
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__pages
Install font 1: (9 0) QSEPYD+Cambria
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/f1.ttf
Embed font: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/f1.ttf 1
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__raw_font_1.ttf
em size: 2048
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/f1.map
Missing space width in font 1: set to 0.001
space width: 0.001
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__tmp_font1.ttf
Add new temporary file: C:\Users\Jens\AppData\Local\Temp/\pdf2htmlEX-a02884/__tmp_font2.ttf

pdf2htmlEX version 0.12
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries:
  poppler 0.26.3
  libfontforge 20140516
  cairo 1.12.14
Default data-dir: D:\Temp\Download\pdf2htmlEX-0.12-win32-static-with-poppler-data/data
Supported image format: png jpg svg

I have tried one of my PDF Files on http://www.zamzar.com/de/convert/pdf-to-html/. They are using pdf2htmlEX and the conversion was amazing good. Not perfect but really wow. So I really like to have a working programm

**Comment by coolwanglu** [comment]
Is there anything wrong in the output?

**Comment by JensHH** [comment]
Output? There is no output because the program crashed. In the temp folder I find:

30.05.2015  17:25    <DIR>          .
30.05.2015  17:25    <DIR>          ..
30.05.2015  17:25                72 f1.map
30.05.2015  17:25            12.360 f1.ttf
30.05.2015  17:25                48 __css
30.05.2015  17:25                 0 __outline
30.05.2015  17:25                 0 __pages
30.05.2015  17:25             1.530 __raw_font_1.ttf
30.05.2015  17:25                 0 __tmp_font1.ttf

**Comment by coolwanglu** [comment]
Did the wiki page about troubleshooting crashes help?

**Comment by JensHH** [comment]
Well, it helped me to send you all the information above. I have now installed FontForge. I can open the font f1.ttf. But I'm not sure if it is right what I see. And I'm not sure if it is enough just to unpack the windows version (http://soft.rubypdf.com/software/pdf2htmlex-windows-verion) or if something is missing. My expectation is that minimum the example should work.

**Comment by JensHH** [comment]
Sorry, I have copied the directory now from D:\Temp\Download\pdf2htmlEX-0.12-win32-static-with-poppler-data to C:\Temp\pdf2html and now it is working with the example. Strange. 

Now I have a problem with my 132 pages PDF but I check that first.

Thanks
Jens

**Comment by volago** [comment]
Hi,
I've also encountered this issue. We've noticed that everything works properly on admin account, but fails in ordinary user account (permissions to dest dir and temp dir were ok). Next we used Process Monitor, a it turned out that pdf2htmlEX.exe tries to save some files in root folder on drive it was launched.

Once we added write permissions to root folder the program finished with successes.

It seems that there are 2 types of temp files: one in configurable temp dir, and the second in root folder. Files are removed after pdf2htmlEX finishes.

**Comment by ankit217** [comment]
@volago 
Hi,
can we provide a path for secondary type temp file created in the root folder?

**Comment by volago** [comment]
Hi @ankit217 

We haven't managed this. We've had a certain compiled version, which didn't provide such a customization as second type temp path..

Though I know, there is a fixed version (we even had a source, but weren't able to compile this).
Unfortunately it was a year ago thus I'a not able to point you to the right repo.

**Comment by ankit217** [comment]
Hi @volago

How to build exe for windows using MinGW? I have followed steps provided [here](http://component-parts.blogspot.in/2015/02/building-pdf2htmlex-for-windows.html). but it gives error while installing dependency libraries. 

I have also used the latest version of all dependency libraries. I think it's due to gcc version used by MinGW installer(6.3.0).

**Comment by JensHH** [comment]
I tried it and failed too. But since Windows 10 can Linux out of the box, exe file is not neccessary anymore

**Comment by volago** [comment]
Hi @ankit217 

A I wrote earlier we weren't able to compile this.

**Comment by ankit217** [comment]
I have compiled successfully. but need to update pdf2htmlEx code as it does not support the latest code of poppler.

**Comment by tmccombs** [comment]
If I simply open and  immediately try to save the Noto Sans Bold CJK (from https://www.google.com/get/noto/help/cjk/) and get a similar error:

Internal Error:
Attempt to output -63677 into a 16-bit field. It will be truncated and the file may not be useful.

I have no idea why this is occurring or how to fix it.
