### ISSUE TITLE
Tables Conversion in Pdf2HtmlEx

### ISSUE THREAD

**Issue by kjayanth** [coolwanglu/pdf2htmlEX#534]
Hi,

We use pdf2htmlEx for converting PDFs to HTMLs for processing them in one of our projects. In the process, we found that there is no consistency (I may be wrong) in converting tables. What we saw was tables are rendered as images in the html but there is no consistency in identifying content of tables as sometimes we see a new class called 'c' being present in tags of its content and sometimes it is not present. 

So is there any definitive way to say that certain set of tags are part of the table ? Any pointers in processing tables rendered in the htmls would be of immense help for us. 

Thanks,
Karthik

**Comment by duanyao** [comment]
PDFs usually don't have any information about tables (tables are just represented as texts and lines), so there is nothing pdf2htmlEX can do. HTML class 'c' denotes 'clip' in pdf2htmlEX, which has nothing to do with tables.

If you want to recognize tables in PDFs, you'll need some [layout analysis](http://en.wikipedia.org/wiki/Document_layout_analysis) tools.
