### ISSUE TITLE
possibilty of getting screenshot pdf image in bigger scale

### ISSUE THREAD

**Issue by dmitrigur** [coolwanglu/pdf2htmlEX#536]
Is it possible to get screenshot image not at 100% of size, but for example 150% or 200%?
this is actually required for cropping small objects at better resolution.

**Comment by duanyao** [comment]
What does "screenshot image" mean? For background images, use `--hdpi` and `-vdpi`.

**Comment by dmitrigur** [comment]
screenshot image is image of whole pdf file.
resolved:
pdftoppm -r<dpi>
