### ISSUE TITLE
Feature Request: Recognize LaTeX Beamer pdfs 

### ISSUE THREAD

**Issue by torwag** [coolwanglu/pdf2htmlEX#538]
Hi,

I am wondering would it be possible to recognize (or flag) latex beamer based documents. They bascially consist of large PDFs for which every animation step is another pdf-page.
Thus, a single presentation slide with e.g. 5 animation steps (as simple as unhide text or images) would consist of 5 pdf pages, each adding more content to the otherwise identically looking page.
Open those PDF files in full view and using page-up and page-down to switch pages gives the impression to have animated presentation slides.

It would be nice if pdf2htmlEX could distinguish between presentation slides and PDF pages and if it could use HTML-based animation steps instead of a new HTML-page. Some programs distinguish the slides by reading the page-numbers (which would only increase for a slide change but not for an animation step). However, people might use a template without page number. I am not aware that anything helpful will be saved into the PDF. But that might be something the beamer LaTeX developers are interested to do (and you might be able to tell them how to save extra data in the pdf).

Next step would be to use one of the usual HTML-based presentation frameworks.

The benefit, people could create the presentation in LaTeX + Beamer which they many prefer, because they use the same tool-chain to write the abstract, paper, graphics, etc.
To get a more interactive version, they could convert the final version to HTML and annotate/modify the HTML version to add  e.g. animations, movies, sound, etc. instead of plain static images only. They could even enable greater interactivity with students. E.g. during a course they follow the lecture and can vote for answers, etc. Basically all the HTML and Javascript fun. 
Many people would love this, but they would not give up on LaTeX+Beamer esp. if they own already >2000 pages of teaching material. ;)

**Comment by coolwanglu** [comment]
It's definitely useful for lots of users, but it's beyond the scope of pdf2htmlEX. I think it is worth a separate project.
