### ISSUE TITLE
'_mkdir' was not declared in this scope

### ISSUE THREAD

**Issue by witwall** [coolwanglu/pdf2htmlEX#540]
when compile windows version, I got this error,

```
pdf2htmlEX-0.13.6/src/util/path.cc: In function 'void pdf2htmlEX::create_directories(const string&)':
pdf2htmlEX-0.13.6/src/util/mingw.h:17:29: error: '_mkdir' was not declared in this scope
 #define mkdir(A, B) _mkdir(A)

```

after research, I found src/util/mingw.h needs

```
#include <direct.h>
```

**Comment by duanyao** [comment]
Thanks for investigate this issue. Can you create a pull request for this change?
Also could you add some instructions on building for windows in the wiki page? I have little experience on it.
https://github.com/coolwanglu/pdf2htmlEX/wiki/Building

**Comment by witwall** [comment]
created a pull request.

and I will update the instructions on building for windows ASAP, I still have some issues when building  python 2.7.3 automatically  under MXE.

**Comment by coolwanglu** [comment]
PR merged. Thanks!
