### ISSUE TITLE
When javascript is disabled, the wrong fonts are used

### ISSUE THREAD

**Issue by lano1106** [coolwanglu/pdf2htmlEX#542]
With no javascript:
![screenshot_2015-06-24_01-40-33](https://cloud.githubusercontent.com/assets/4829131/8323478/09562648-1a13-11e5-894c-53dd5411260f.png)
With javascript enabled:
![screenshot_2015-06-24_01-41-26](https://cloud.githubusercontent.com/assets/4829131/8323481/119f3b28-1a13-11e5-82d9-72900f55c269.png)

http://hackinglinkedinformula.com/index.html
has been generated with

pdf2htmlEX version 0.13.6
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.33.0
  libfontforge 20150506
  cairo 1.14.2
Default data-dir: /home/lano1106/dev/pdf2htmlEX/pkg/pdf2htmlEX/usr/share/pdf2htmlEX
Supported image format: png jpg svg

Output slightly customized from:
http://hackinglinkedinformula.com/LinkedINHackingFormulaSalesPage.pdf

**Comment by lano1106** [comment]
might be important as well. Here is the cmdline used:
pdf2htmlEX --external-hint-tool=ttfautohint --fit-width 800 --embed CfiJO --optimize-text 1 ../LinkedINHackingFormulaSalesPage.pdf LinkedInHackingFormula.html

**Comment by duanyao** [comment]
Can't reproduce. JS should have no effect on font in pdf2htmlEX.
What browsers you tested with? How did you disable JS?

**Comment by lano1106** [comment]
Firefox 38 with Noscript plugin:
https://noscript.net/

**Comment by lano1106** [comment]
I agree with you that it should not have effect but by toggling JS on and off I flip back and forth from the 2 versions displayed in OP.

This has been reported by someone using a old Firefox version that was making it easier to turn off JS:
Firefox
20.0

**Comment by duanyao** [comment]
NoScript also block web fonts by default, and this is configurable (options->embeddings-Forbid @font-face).

**Comment by lano1106** [comment]
Bingo!
Non-issue thanks!
