### ISSUE TITLE
Missing letters with Safari browser on MacOS

### ISSUE THREAD

**Issue by lano1106** [coolwanglu/pdf2htmlEX#543]
PDF file:
http://hackinglinkedinformula.com/LinkedINHackingFormulaSalesPage.pdf
Output customized:
http://hackinglinkedinformula.com/index.html
With cmdline:
pdf2htmlEX --external-hint-tool=ttfautohint --fit-width 800 --embed CfiJO --optimize-text 1 ../LinkedINHackingFormulaSalesPage.pdf LinkedInHackingFormula.html

pdf2htmlEX version 0.13.6
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.33.0
  libfontforge 20150506
  cairo 1.14.2
Default data-dir: /home/lano1106/dev/pdf2htmlEX/pkg/pdf2htmlEX/usr/share/pdf2htmlEX
Supported image format: png jpg svg

Look for the words 'profile', 'starting' and 'tips', they miss the letters 'ti', and 'fi'.

![macos_safari_font_errors](https://cloud.githubusercontent.com/assets/4829131/8323535/e20716a0-1a13-11e5-9394-f3bab58a4208.jpg)

**Comment by duanyao** [comment]
Is this issue specific to Safari browser on MacOS? How other browsers on MacOS behave? Looks like a safari bug.

**Comment by lano1106** [comment]
No idea. I am not a Mac user. This has been reported to me by someone else.
I agree to your diagnostic.
Feel free to close this issue.

**Comment by josiasmontag** [comment]
I can confirm this issue of missing letters. 
Safari 8.0.7 (OSX) and latest mobile Safari (iOS 9 beta 3, also all earlier iOS versions as far as I see).
pdf2htmlEX 0.13.6

Screenshot of document inspector:
![buzzback_com_images_cftest2_html_und_buzzback_com_images_cftest2_html](https://cloud.githubusercontent.com/assets/1945577/8768044/13c0bcd8-2e72-11e5-9350-2869815393fd.jpg)



Any way I can help to debug further?

**Comment by duanyao** [comment]
@josiasmontag Maybe you want to report this issue to Apple or try [webcom](pathttps://webcompat.com/).

**Comment by dfurber** [comment]
I've just been diagnosing the same bug report, and can reproduce it in Safari/Mac. The culprit (in my case at least) is the font family "ff1". If I edit class ff1 to use any other font-family, I see the missing letters. ff0 looks okay but is a serif font. ff2 and above show the letters, but also look like ransom notes with the other ff1 styles applied.

**Comment by maxholman** [comment]
A workaround to display the missing characters is to deactivate common ligatures for Webkit, with the following CSS:

`-webkit-font-variant-ligatures: no-common-ligatures;`
