### ISSUE TITLE
ToUnicode CMap is not valid and got dropped

### ISSUE THREAD

**Issue by lano1106** [coolwanglu/pdf2htmlEX#545]
Got the same problem than the one reported in:
https://github.com/coolwanglu/pdf2htmlEX/issues/441

PDF file:
http://hackinglinkedinformula.com/LinkedINHackingFormulaSalesPage-libre.pdf
Output customized:
http://hackinglinkedinformula.com/index.html

Most of the text, except the headline and the first 2 paragraphs, if you copy & paste, will be garbled. Cut & pasting the same text from the pdf is fine.

How the pdf was produced:
With LibreOffice Draw
The problematic font is Microsoft Calibri

With cmdline:
pdf2htmlEX --external-hint-tool=ttfautohint --fit-width 800 --embed CfiJO LinkedINHackingFormulaSalesPage-libre.pdf LinkedInHackingFormula.html
No glyph for a standard character to derive standard width and height.
Please check the documentation for a list of script-specific standard characters,
or use option `--symbol'.
ToUnicode CMap is not valid and got dropped for font: 4
ToUnicode CMap is not valid and got dropped for font: 5
No glyph for a standard character to derive standard width and height.
Please check the documentation for a list of script-specific standard characters,
or use option `--symbol'.
No glyph for a standard character to derive standard width and height.
Please check the documentation for a list of script-specific standard characters,
or use option `--symbol'.
No glyph for a standard character to derive standard width and height.
Please check the documentation for a list of script-specific standard characters,
or use option `--symbol'.
Working: 1/1

pdf2htmlEX version 0.13.6
Copyright 2012-2014 Lu Wang coolwanglu@gmail.com and other contributors
Libraries:
poppler 0.33.0
libfontforge 20150506
cairo 1.14.2
Default data-dir: /home/lano1106/dev/pdf2htmlEX/pkg/pdf2htmlEX/usr/share/pdf2htmlEX
Supported image format: png jpg svg

**Comment by lano1106** [comment]
Using the suggested workaround of using switch --tounicode 1 do correct the output.

**Comment by coolwanglu** [comment]
So what's the bug/issue? It seems to me that there's something wrong in the PDF file.
