### ISSUE TITLE
Paths for input.pdf are unsupported

### ISSUE THREAD

**Issue by mirhl** [coolwanglu/pdf2htmlEX#546]
**Error: Cannot open ./C:\p2h\asn.html for writing**

This happens every time you provide a path (*C:\p2h\input.pdf*) instead of just *input.pdf*
Windows 7x64, version 0.13.6

Ok, this might or might not be somewhat related to #504

**Comment by mirhl** [comment]
Still present in 0.14.6

**Comment by witwall** [comment]
It is a bug, for now need replace "\" with "/ ", for example, replace C:\p2h\input.pdf  with C:/p2h/input.pdf

**Comment by witwall** [comment]
@mirhl fixed, please download the update version.

**Comment by mirhl** [comment]
Fixed
