### ISSUE TITLE
Option to save images individually?

### ISSUE THREAD

**Issue by antoniobrandao** [coolwanglu/pdf2htmlEX#548]
The output seems to consolidate all images into the background image. I understand this is the default for obvious reasons but in my case the publisher needs to animate individual images of the documents. I couldn't find an option to achieve this in the documentation, is there any?

**Comment by duanyao** [comment]
With SVG background image and `--svg-embed-bitmap 0` you can save images individually (only RGB or Gray JPEG bitmaps in PDF are supported now). But you need to animate the images in the SVG files, not in the HTML.

**Comment by antoniobrandao** [comment]
Thanks for the reply. I read about the use of SVG, tried in my system but got this error:

    01:04 ~/pdftests/ pdf2htmlEX --embed cfijo --dest-dir output --fit-width 2048 --bg-format svg test.pdf
    Image format not supported: svg

It's a fresh install of pdf2htmlEX installed with homebrew. How to enable SVG support?

**Comment by duanyao** [comment]
Build the recent source, and SVG should be enabled by default.
https://github.com/coolwanglu/pdf2htmlEX/wiki/Building

**Comment by duanyao** [comment]
Feel free to comment if you have other problem.
