### ISSUE TITLE
Cannot open file /data/compatibility.min.js for embedding

### ISSUE THREAD

**Issue by mirhl** [coolwanglu/pdf2htmlEX#553]
Windows x64 with new 0.14.6

When I enabled debug view I see all temp paths are like this: C:\Users\xxx\AppData\Local\Temp***//***pdf2htmlEX-a08800

This last path is instead C:\Users\xxx\Desktop\folder***/***data/compatibility.min.js

Notice the first slash is single. Could this be culprit?

**Comment by mirhl** [comment]
... Ok it was way simpler..
The file is just not there. Not sure if this should be considered an issue here on on the win32 maintainer.

**Comment by witwall** [comment]
please download update version.

**Comment by mirhl** [comment]
Perfect
