### ISSUE TITLE
Installation issue in CentOS 6.6

### ISSUE THREAD

**Issue by karthikpasc** [coolwanglu/pdf2htmlEX#558]
Hi,
I try to install pdf2htmlEX v0.13.6 in my CentOS 6.6 machine.
It require fontforge latest version in compilation time.
But machine have fontforge-20090622-3.1.el6 version only.
Its enough to install the above version of pdf2htmalEX or needed latest version.
Any alternate way available to install fontforge latest version in my machine.
Because i raised my request too many times but didn't get any response from fontforge.
If you have any installation procedure for above version please share it with me.

**Comment by coolwanglu** [comment]
That version is too old, pdf2htmlEX won't work well with it.
