### ISSUE TITLE
installation quit with below error

### ISSUE THREAD

**Issue by karthikpasc** [coolwanglu/pdf2htmlEX#559]
/pdf2htmlEX-0.13.6]# cmake .
-- checking for module 'poppler>=0.25.0'
--   found poppler, version 0.30.0
-- checking for module 'cairo>=1.10.0'
--   package 'cairo>=1.10.0' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:28 (pkg_check_modules)

Trying to locate cairo-svg...
CMake Error at CMakeLists.txt:47 (message):
  Error: no SVG support found in Cairo

-- Configuring incomplete, errors occurred!
See also "/root/pdf2htmlEX-0.13.6/CMakeFiles/CMakeOutput.log".

**Comment by amirag2984** [comment]
do u resolve it? i m also facing the same issue

**Comment by karthikpasc** [comment]
Hi,
@amirag2984 yes but its work only in latest CentOS 7.
Earliar Versions till face the same issue.
But my requirement is install this tool in CentOS 6.4.

**Comment by coolwanglu** [comment]
As shown in the message "Error: no SVG support found in Cairo"

Either you install cairo with svg support, or disable svg support.
