### ISSUE TITLE
What about generating svg export ?

### ISSUE THREAD

**Issue by parisni** [coolwanglu/pdf2htmlEX#560]
Hi, 

great job for your pdf -> html converter.

I wonder if this would be possible to extend your tool to an pdf -> svg converter

I guess this would be wonderfull.

Thanks for answer

**Comment by coolwanglu** [comment]
There's already such a tool in poppler, please try it.

**Comment by parisni** [comment]
I 've allready tested it : it considers characters as images. No way to select text in the output then.
 Your parser is much better. what about that

**Comment by coolwanglu** [comment]
That's most likely browser bugs. If I remember correctly, Firefox has this bug for a long time, but Chrome should work.
And it doesn't matter how the svg is generated, in fact the svg generation code are from poppler.

**Comment by parisni** [comment]
What I mean is poppler transforms pdf characters not as svg text, but as image. Nothing about chrome or firefox.
