### ISSUE TITLE
Option to save SVG-Images individually

### ISSUE THREAD

**Issue by HeimMatthias** [coolwanglu/pdf2htmlEX#561]
Would it be possible to split up the background SVGs (or the background PNGs, for that matter) into smaller chunks, and -- if possible -- to embed these next to the portion of the text where they appear?
 
Personal reason: I'm attempting to split the HTML-Output mid-page, where my sub-chapters start. And while this works, the background-image doesn't divide so easily.

The Math behind the creation of "chunks" shouldn't be too advanced, just a matter of regrouping <path>-Elements based on their matrix-transformations and d-Tags. There probably would have to be a command-line option for the maximal distance a vector element can take from another before it's moved into its own SVG. Embedding them at the right place is probably the more difficult task.
 
Have you thought about this possibility at all?

(BTW: What a wonderful tool! Thank you so much.)

**Comment by coolwanglu** [comment]
This is probably not something a converter should do. Maybe you can find such a tool for PDF files, and split the files before converting them into HTML.
