### ISSUE TITLE
Reflow documents?

### ISSUE THREAD

**Issue by vext01** [coolwanglu/pdf2htmlEX#563]
Hi,

I had a play with pdf2htmlEX last week, and I was pretty impressed, but it didn't quite meet my requirements.

I expect the answer is no, but do you think pdf2htmlEX could ever have support to reflow the document text to make it easier to read on mobile devices?

I am a computer scientist, and I convert my publications to HTML using htlatex. htlatex is pretty poor. Even when it's not crashing, I only use it's output as a basis, and spend some hours "mastering" the output. Even then the HTML source is awful. Sadly it is still the best we have if you want your text to reflow.

I've also tried hevea and a couple of others with no joy :(

Thanks

**Comment by coolwanglu** [comment]
Yes this feature has been one of the most desired ones. Yet it's not easily to do so.

Here's the wiki page for discussions: https://github.com/coolwanglu/pdf2htmlEX/wiki/Reflowable-Text

It might be relatively easy if there's corresponding tag information in PDF. And you might also try if this works for you http://latex2html5.com/
