### ISSUE TITLE
z-layers not converted in correct order

### ISSUE THREAD

**Issue by asinning** [coolwanglu/pdf2htmlEX#568]
Sometimes publishers will leave data from different versions of a title (e.g. softcover vs. hardcover) in a back layer of the document.  

Here's the pdf view of the lower-right corner of the back-cover of the document:

![screen shot 2015-09-02 at 1 08 25 pm](https://cloud.githubusercontent.com/assets/1169946/9639847/b44064f0-5173-11e5-8f4a-185b0bc77923.png)

Here's a screenshot of the html output:

![screen shot 2015-09-02 at 1 10 33 pm](https://cloud.githubusercontent.com/assets/1169946/9639896/060427ea-5174-11e5-95ad-4a63bbc8603e.png)

I have a version of the pdf with all of the pages except for the back cover removed.  It's 1.8MB zipped.  I can send it to you if you would like.

Thanks!  So far this looks like a great product.  We will quite likely be using it to convert approximately 100K titles.

**Comment by egrubbs** [comment]
Try
```
  pfd2htmlEX --correct-text-visibility 1
```
It worked for me. I'm not sure why it is turned off by default.

**Comment by asinning** [comment]
Great! Issue closed
