### ISSUE TITLE
Need to know compatible Cent OS Version

### ISSUE THREAD

**Issue by karthikpasc** [coolwanglu/pdf2htmlEX#570]
Hi,
I want to know which CentOS version is compatible to install latest pdf2htmlEX. Please reply ASAP.

**Comment by sathishks** [comment]
@coolwanglu : Any update on this.

**Comment by coolwanglu** [comment]
I haven't got time to set up a Cent OS myself.
You can just check the dependencies in the wiki page.

**Comment by karthikpasc** [comment]
@coolwanglu Your wiki page is not clear. 
That is the reason to am asking here.
Every time we face lot of head ache to install pdf2htmlEX in linux systems.
Kindly share the proper document if you have for linux systems.

**Comment by coolwanglu** [comment]
Which part?
I believe the most important dependencies, as well as the version numbers
are listed in the doc:https://github.com/coolwanglu/pdf2htmlEX/wiki/Building

**Comment by karthikpasc** [comment]
@coolwanglu 
We already followed above wiki for our package compilation.
But it not work.
Most of the packages mentioned in yum install not come with cent.repo and epel.repo.
After Installed all the required dependency also, we got dependencies missed error in our pdf2htmlEX compilation.
But our previous pdf2htmlEX version compilations, we never got this type of errors.
Our whole process stopped due to this.
Already i posted my error details in your site.

**Comment by coolwanglu** [comment]
@karthikpasc I answered in that post. The command in the wiki is for Fedora but not for Cent OS.
I also added a line in the wiki page about how to disable it.

**Comment by karthikpasc** [comment]
@coolwanglu  i believe you have enough knowledge about OS.
Both Fedora and Cent OS are from same family.
If it work in fedora, 
Surely it works in Cent OS too.
I know how to disable libs in compilation.
This option comes default with all packages.
But it affect some of our features.
I think you understand.
