### ISSUE TITLE
How I can convert to pdf, generated HTML pages!

### ISSUE THREAD

**Issue by dmitrirussu** [coolwanglu/pdf2htmlEX#576]
I have generated a pdf file to html, now after some changes on my editor I want to convert back to pdf. is possible this todo, using pdf2htmlEX

**Comment by egrubbs** [comment]
The best tool out there is wkhtmltopdf.
There is some issue with the text/fonts produced by pdf2htmlex that causes problems with wkhtmltopdf, so I have to use this option:
```
pdf2htmlEX --proof 1
```
To make wkhtmltopdf use the right css, it needs to be run with this option:
```
wkhtmltopdf --print-media-type
```

**Comment by AntoniosHadji** [comment]
I have used Pandoc for converting html to pdf with good results.
http://pandoc.org/README.html#creating-a-pdf

**Comment by coolwanglu** [comment]
Some tools may work with specific PDF files, but in general this is not supported by pdf2htmlEX.
