### ISSUE TITLE
full page images?

### ISSUE THREAD

**Issue by MarcGodard** [coolwanglu/pdf2htmlEX#583]
Is there a way to get full page images? the fallback option still removes white spaces on the margins, but i would like that included in the images.

**Comment by MarcGodard** [comment]
I am guessing this project is no longer being improved on or is inactive?

**Comment by duanyao** [comment]
I believe removing margins of background images reduces memory consumption of browsers. Why the margins are important to you?

**Comment by MarcGodard** [comment]
Because I am using the images for a zoom in effect in a modal and the white spacing around it is not constant and therefore creating difficulty in grabbing the correct portion of the image.

**Comment by duanyao** [comment]
If all you want is converting PDF to full page images, maybe poppler's [`pdftocairo`](http://manpages.ubuntu.com/manpages/precise/man1/pdftocairo.1.html) or pdfbox's [`PDFToImage`](https://pdfbox.apache.org/1.8/commandline.html) do a better job.

**Comment by MarcGodard** [comment]
Actually it wouldn't, 1) I already use your system for the HTML, and 2) What I do is make the user click on the HTML and a popup bring up that section (cutout) in an image and zoomed in. The problem is calculating what part of that image to bring up because it doesn't match the HTML version. If the PDF was a full image I can easily calculate the HTML version to image, but because of the unpredictable white space, your image version cannot be matches this way.

**Comment by MarcGodard** [comment]
@coolwanglu Don't you think this would be a good option? If you can help me point to where in the code I can add this, I could do it.

**Comment by coolwanglu** [comment]
I wonder if the `use_cropbox` parameter would help

**Comment by MarcGodard** [comment]
I will take a look next time I am on that project. Thanks.
