### ISSUE TITLE
Image filter

### ISSUE THREAD

**Issue by dmitrigur** [coolwanglu/pdf2htmlEX#585]
Hello
i use "pdfimages" command to get images from pdf file
is it possible to filter images in terms of their sizes, to cut off small images which are basically some bars, lines, single pixel images? 

thank you

**Comment by duanyao** [comment]
What purpose do you want to achieve? Small images are not always less important than big images. In fact in some PDFs a big "image" may be actually a tiled one by many small images.

**Comment by coolwanglu** [comment]
Seems that the poppler mailing list is a better place to discuss about it, as pdfimages is part of poppler.
