### ISSUE TITLE
many fonts with minor differences

### ISSUE THREAD

**Issue by sporritt** [coolwanglu/pdf2htmlEX#586]
Hi

This may or may not be a bug in your estimation; primarily I'm asking for your advice.  We have a PDF with around 500 pages, which poppler reports as containing 192 fonts. Looking at the font names we can see there are many duplicates, and so running it through ghostscript to optimize it (using the command suggested in your wiki) brings that number down to 19. However, pdf2htmlEX creates about 80 or so fonts when it converts the PDF to HTML, and if you inspect the fonts you can see there are often very minor differences, for instance:

![image](https://cloud.githubusercontent.com/assets/262720/10679391/11310e68-7964-11e5-9ba2-74163ff337b0.png)

and

![image](https://cloud.githubusercontent.com/assets/262720/10679401/1cbda246-7964-11e5-989f-aee439b94870.png)

in this case the delta is so minor it is almost undetectable; it kind of looks like the delta is perhaps just the whitespace in one or more of the glyphs.

We've tried the flag that creates fewer fonts but it does not seem to make a difference.

My client is interested in getting the most solid solution for this that they can, and if that means either consulting you to assist or funding work on the open source project there is a good chance they will be amenable.  My email address is listed on my profile if you would like to contact me on that front.

thanks!

**Comment by sporritt** [comment]
..in fact looking at this one I see that the digits are kind of different, but the digits in the first example look kind of dodgy.

**Comment by aklatzke** [comment]
What flags did you use when running this?

**Comment by DoctorZIP** [comment]
for example I use:
pdf2htmlEX --optimize-text 1 --tounicode 1 --no-drm 1 --space-threshold 0.1 --decompose-ligature 1 --process-outline 0 --font-format ttf --embed cfiO --process-outline 0 sample.pdf --dest-dir ./result

Every time for same pdf I got different font checksums

**Comment by coolwanglu** [comment]
I believe this is beyond the scope of pdf2htmlEX, it looks to me a PDF optimization task: to reduce the number of fonts without altering the rendering.

**Comment by coolwanglu** [comment]
https://github.com/coolwanglu/pdf2htmlEX/wiki/Unfeatures
