### ISSUE TITLE
I install pdf2htmlEX successfully, but it always report a error when I run the program.

### ISSUE THREAD

**Issue by piaolinzhi** [coolwanglu/pdf2htmlEX#588]
I install pdf2htlEX on a  centos7 docker server. It's a very very very hard work for a java programer. 
When I run the program, it always report the error below.

[root@b147304742d2 pdf]# pdf2htmlEX --help
pdf2htmlEX: error while loading shared libraries: libpoppler.so.56: cannot open shared object file: No such file or directory

I installed poppler 0.37.0 and poppler-data 0.4.7 from source code. before make install pdf2htmlEX  and the process of make install pdf2htmlEX successed finally.
I don't know what mistake I made.

PS: The Dockerfile as below :

#Dockerfile to build a pdf2htmlEx image oracle jdk8 tomcat7 

#FROM tomcat:8
#
ENV PDF2HTMLEX_HOME /pdf_temp
RUN mkdir -p "$PDF2HTMLEX_HOME"
WORKDIR $PDF2HTMLEX_HOME
#Install git and all dependencies
RUN yum group install -y "Development Tools"
RUN yum install -y  cmake gcc gnu-getopt libpng-devel cairo-devel  libspiro-devel freetype-devel   libjpeg-turbo-devel python-devel pango-devel libxml2-devel libtool-ltdl-devel git
#install poppler poppler-data
RUN curl -fSLO http://poppler.freedesktop.org/poppler-0.37.0.tar.xz && tar -xvf poppler-0.37.0.tar.xz
RUN cd poppler-0.37.0 &&./configure  --enable-xpdf-headers --prefix=/usr&& make && make install
RUN curl -fSLO http://poppler.freedesktop.org/poppler-data-0.4.7.tar.gz && tar -xvf poppler-data-0.4.7.tar.gz
RUN cd poppler-data-0.4.7 && make prefix=/usr install

#install fontforge
RUN git clone https://github.com/coolwanglu/fontforge.git fontforge.git
RUN cd fontforge.git && git checkout pdf2htmlEX && ./autogen.sh && ./configure  --enable-xpdf-headers --prefix=/usr && make && make install

#config pkg-config path
ENV PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig/:/usr/lib/pkgconfig/

#Clone and install the pdf2htmlEX git repo
RUN git clone git://github.com/coolwanglu/pdf2htmlEX.git
RUN cd pdf2htmlEX && cmake . && make && make install

#clean the image
RUN rm poppler-data-0.4.7.tar.gz && rm poppler-0.37.0.tar.xz && yum clean all
RUN mkdir -p /pdf
VOLUME /pdf
WORKDIR /pdf
CMD ["pdf2htmlEX"]

**Comment by duanyao** [comment]
Run the follow commands to check the installation of poppler:
```
ldd /usr/local/bin/pdf2htmlEX | grep poppler
find /usr/local/lib -name "libpoppler.so*"
```

**Comment by piaolinzhi** [comment]
@duanyao  You are right. I installed the poppler right but did not refresh the cache of dynamic linker of system. It works after adding `RUN ldconfig -v` in my dockerfile.
Thanks a lot!

**Comment by piaolinzhi** [comment]
Here is my docker file finnally.
`
#Dockerfile to build a pdf2htmlEx image oracle jdk8 tomcat7 
#FROM jdk_you_build_before 
#
ENV PDF2HTMLEX_HOME /pdf_temp
RUN mkdir -p "$PDF2HTMLEX_HOME"
WORKDIR $PDF2HTMLEX_HOME
#Install git and all dependencies
RUN yum group install -y "Development Tools"
RUN yum install -y  cmake gcc gnu-getopt libpng-devel cairo-devel  libspiro-devel freetype-devel   libjpeg-turbo-devel python-devel pango-devel libxml2-devel libtool-ltdl-devel git
#install poppler poppler-data
RUN curl -fSLO http://poppler.freedesktop.org/poppler-0.37.0.tar.xz && tar -xvf poppler-0.37.0.tar.xz
RUN cd poppler-0.37.0 &&./configure  --enable-xpdf-headers --prefix=/usr&& make && make install
RUN curl -fSLO http://poppler.freedesktop.org/poppler-data-0.4.7.tar.gz && tar -xvf poppler-data-0.4.7.tar.gz
RUN cd poppler-data-0.4.7 && make prefix=/usr install

#install fontforge
RUN git clone https://github.com/coolwanglu/fontforge.git fontforge.git
RUN cd fontforge.git && git checkout pdf2htmlEX && ./autogen.sh && ./configure  --enable-xpdf-headers --prefix=/usr && make && make install

#config pkg-config path
ENV PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig/:/usr/lib/pkgconfig/

#Clone and install the pdf2htmlEX git repo
RUN git clone git://github.com/coolwanglu/pdf2htmlEX.git
RUN cd pdf2htmlEX && cmake . && make && make install

#refresh lib reference
RUN ldconfig -v

#clean the image
RUN rm poppler-data-0.4.7.tar.gz && rm poppler-0.37.0.tar.xz && yum clean all
RUN mkdir -p /pdf
VOLUME /pdf
WORKDIR /pdf
CMD ["pdf2htmlEX"]
`
