### ISSUE TITLE
Convert using semantic elements

### ISSUE THREAD

**Issue by andrezzoid** [coolwanglu/pdf2htmlEX#592]
Hi there,

first of all, congrats on this tool, it's awesome!

I know there are already a couple of SEO issues, that's not really my goal here.

I want to use pdf2htmlEX to convert a series of Portuguese goverment documents, made available in PDF, and present them in a website with a better search engine, annotations and other stuff to make understading the law easier.

pdf2htmlEX is great for that purpose, but I'd love to see it convert to an HTML that uses semantic elements (**p** when it's a paragraph, **hX** when it's a title, **ul** when it's a list, and so on and so forth). I also don't need the converted html to be exactly equal to the original document, so those spans between words are also not important to me. Basically a clean, semantic conversion. Is that already possible or somewhere in the roadmap?

**Comment by duanyao** [comment]
Most PDF files don't have semantic information (except [Tagged PDF](http://blogs.adobe.com/acrolaw/2006/01/understanding_t_1/)), so it is challenging for pdf2htmlEX (and any pdf converter) to produce semantic output.

What you need seems a [layout analysis](https://en.wikipedia.org/wiki/Document_layout_analysis) tool, and [pdfminer](https://github.com/euske/pdfminer) has [one for pdf](https://euske.github.io/pdfminer/#pdf2txt).

Of cause it would be nice to incorperate some sort of layout analysis feature like pdfminer into pdf2htmlEX, so we could have both semantic and high fidelity output, however it may turn out complicated to do.

**Comment by andrezzoid** [comment]
Thank you for enlightning me! :smiley: I'll look into it.

And is there any way to remove the span tags between words and replace it with normal spaces? That would help my use case a lot.

**Comment by duanyao** [comment]
`--space-as-offset 1 --optimize-text 1` may help.

**Comment by andrezzoid** [comment]
Thanks a lot for your help!

**Comment by fmalina** [comment]
Have a look at https://github.com/fmalina/transcript
It is a post processing tool for PDFtoHMLEx output providing semantic HTML based on visual design conventions.

**Comment by coolwanglu** [comment]
@fmalina Interesting project! Thanks for sharing.
