### ISSUE TITLE
Can pdf2htmlEX export inline css?

### ISSUE THREAD

**Issue by linb** [coolwanglu/pdf2htmlEX#600]
Can pdf2htmlEX export inline css?

For example:

Currently, it outputs:
  --------------------------------------------
   html
  ------
      <div class="t m0 x1 h2 y1 ff1 fs0 fc0 sc0 ls0 ws0"> </div> 

  css
  ------
    .x1 {
    left: 558.220000px;
    }
    .h2 {
    height: 24.556641px;
    }
  --------------------------------------------

  I need:
  --------------------------------------------
    <div style="position:absolute;left: 558.220000px;height: 24.556641px;..."> </div>

**Comment by coolwanglu** [comment]
No for now.

**Comment by wanghaisheng** [comment]
@linb   did you ever success with other tools . i tried many ones  and got no luck
