### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by haydenbleasel** [coolwanglu/pdf2htmlEX#605]
Hello,

I've converted a few documents using pdf2htmlEX but I appear to be having trouble with one specific document. The document appears white while the console shows:

```
Uncaught SyntaxError: Unexpected end of input
y @ document.html:267
L @ document.html:279
E @ document.html:280
(anonymous function) @ document.html:269
```

The lines of code specified attribute to `pdf2htmlEX.js` (Core UI functions for pdf2htmlEX). Any thoughts on how to start fixing, or even debugging, this problem?

**Comment by coolwanglu** [comment]
If you build the source, you will get uncompressed js files, then you can replace installed js files with these uncompressed ones, and get better stack trace.

**Comment by haydenbleasel** [comment]
Hey, sorry @coolwanglu, I was using Cheerio with this and used `{ decodeEntities: true}` which messed up the inline scripts. My bad :)
