### ISSUE TITLE
Error compiling fontforge when installing on ubuntu

### ISSUE THREAD

**Issue by DarkStar1** [coolwanglu/pdf2htmlEX#606]
I am trying to install this on an ubuntu 14.04 now with linuxbrew and I was currently stuck on the following error:
My C compiler works (can even compile 32bit objects)
The following is the output from console:

> ~$ brew install pdf2htmlex
> ==> Downloading https://github.com/coolwanglu/pdf2htmlEX/archive/v0.13.6.tar.gz
> Already downloaded: /home/lanre/.cache/Homebrew/pdf2htmlex-0.13.6.tar.gz
> ==> Patching
> patching file 3rdparty/poppler/git/CairoFontEngine.cc
> Hunk #1 succeeded at 421 with fuzz 2.
> ==> Cloning https://github.com/coolwanglu/fontforge.git
> Updating /home/lanre/.cache/Homebrew/pdf2htmlex--fontforge--git
> ==> Checking out branch pdf2htmlEX
> ==> ./autogen.sh
> ==> ./configure --prefix=/home/lanre/.linuxbrew/Cellar/pdf2htmlex/0.13.6_7/fontforge --without-libzmq --without-x --without-iconv 
> Last 15 lines from /home/lanre/.cache/Homebrew/Logs/pdf2htmlex/02.configure:
> checking host system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking how to create a pax tar archive... gnutar
> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking for style of include used by make... GNU
> checking for gcc... /usr/bin/gcc-4.8
> checking whether the C compiler works... no
> configure: error: in `/tmp/pdf2htmlex--fontforge20160124-518-102e7og':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
I, however, found this script for the [manual installation!](https://gist.github.com/rajeevkannav/d07f822e209a22d07176) whilst I was searching for resolutions and it works just fine for ubuntu.

**Comment by Numerizen** [comment]
Just wanted to drop a few lines to give a big thank you for this : I've been banging my head against compilation errors for three days. Had no luck with manual building, brew (same exact error you had, and yes, 'brew hello' worked fine so it's something with pdf2htmlEX) or package install (segfault).

Also wanted to let people know the script worked on Debian Wheezy for me.

**Comment by coolwanglu** [comment]
It appears that homebrew is using my fork of fontforge, which is not well maintained. 

Thanks for mentioning the input. I'll add it to the wiki
