### ISSUE TITLE
Different fonts within almost similar files

### ISSUE THREAD

**Issue by longpants** [coolwanglu/pdf2htmlEX#608]
Hi there,
Thanks for the great efforts you put in this tool. I was checking out a few converters, but this one beats them all!

I'm using pdf2htmlEX by command line to generate HTML pages I can test / analyse for differences.
Now the good thing is that your code provides different styles to identify different fonts, so I can rely on class styles to identify sections / texts within the HTML.

But now for my issue:
In case I have a PDF with (let's assume) texts with fonts h1, h2 and h3, the converter creates ff1, ff2, ff3.
But when I have a PDF with only fonts h2 and h3, the converter also creates ff1 and ff2 font styles

Is there a way to 'set' fonts so the generated class will be identical?

**Comment by coolwanglu** [comment]
Not sure if this is worth a dedicated parameter, but you can hack `font.cc` where the fonts are named, maybe you can use the internal ID as part of the filename.
