### ISSUE TITLE
Deterministic output, or output without any styles, for PDF comparison

### ISSUE THREAD

**Issue by nuest** [coolwanglu/pdf2htmlEX#617]
Hi! Great library you have there, which I want to (mis?)use for comparing two PDFs (pointers to alternatives appreciated, of course). I have different PDFs based on the same workflow and source files, but from different systems and want to make sure they have the same content.

When I run pdf2htmlEX on both files (not embedding anything, i.e. `--embed cfijo`) the resulting outputs marginally differ in the names of the CSS classes, e.g. `y16d` becomes `y16c`.

**My questions:**
* How are the class names generated? Are they completely deterministic? It could very well be that pdf2htmlEX correctly carries on a difference in the PDFs here (`diffpdf` does not report any difference), but I'd like to be sure.
* Is there an option to get a plain HTML _without any CSS classes_? This of course has the risk of not picking up on actual differences between the files, but for starters that would be fine.

**Comment by coolwanglu** [comment]
This has never been considered in the code, but I believe you will always get the same output for the same input.

Each `y` class means a `y`-value for the elements, usually a new class is generated when a new value is found.

I don't think pdf2htmlEX is suitable for your task. How about `pdftotext`, or decompress the PDF files (e.g. with pdftk) and simply `diff` the PDF files?

**Comment by nuest** [comment]
I have tested pdftotext, yes, but was not aware of pdftk uncompress - thanks for the hint!

And thanks for your assessment of the situation.
