### ISSUE TITLE
What's the best way to convert back to PDF?

### ISSUE THREAD

**Issue by christianbundy** [coolwanglu/pdf2htmlEX#629]
I'm working on a set of HTML files that were created with pdf2htmlEX, but I'm trying to get them back in PDF format. Is there a recommended approach?

**Comment by taveras** [comment]
you may want to consider exploring these previous issue: https://github.com/coolwanglu/pdf2htmlEX/issues/576

**Comment by christianbundy** [comment]
Thank you!
