### ISSUE TITLE
Split background images

### ISSUE THREAD

**Issue by Costyv95** [coolwanglu/pdf2htmlEX#631]
Hi. I've noticed that pdf2htmlEX creates a single background image for any page of my pdf . Is there any option so that I get every image element on each page (with absolute position, of course) or there is no way to do that and i have to use another library to extract the images separately and then combine these results together ?

**Comment by coolwanglu** [comment]
Previously I had a partial patch for that, but didn't managed to merge it.
So far it's not supported in pdf2htmlEX, but maybe you can try the SVG format

**Comment by Costyv95** [comment]
Can u explain a bit the svg solution? I have a pdf, not a svg and from what i notoced there is no perfect tool to convert a pdf to a svg file. Is there an option into pdf2htmlEx that does that?

**Comment by coolwanglu** [comment]
Please read the manpage about the `--bg-format` param.

**Comment by Costyv95** [comment]
Thank you. This is exactly what I wanted . Nice tool.
