### ISSUE TITLE
Is the output file pdf2htmlEX.js static?

### ISSUE THREAD

**Issue by lmtoo** [coolwanglu/pdf2htmlEX#700]
I meet a requirement : add page infomation when scrolling page.
so I have to alter the output html or pdf2htmlEX.js, but I don't have so much time to read pdf2htmlEX source, I have to make sure the file pdf2htmlEX.js is static, or how I can alter the pdf2htmlEX.js?

**Comment by duanyao** [comment]
What do you mean by 'static'? You can provide a customized `pdf2htmlEx.js` via `--data-dir` option (https://github.com/coolwanglu/pdf2htmlEX/wiki/Command-Line-Options ).

**Comment by lmtoo** [comment]
@duanyao thank you , I have replaced /usr/local/share/pdf2htmlEX/pdf2htmlEX.min.js with my custom file, and the output pdf2htmlEX.min.js is my custom file.
