### ISSUE TITLE
Try to disable FontForge timestamp generation

### ISSUE THREAD

**Issue by taktoa** [coolwanglu/pdf2htmlEX#708]
The fonts generated by FontForge include a timestamp, which is unnecessary and makes it harder to, e.g.: use the output of pdf2htmlEX in a git repository (the current mitigation I'm using is `--font-format svg`, which makes the diffs quite small). I don't know how feasible it is, but not having that timestamp would be quite nice. I might look into fixing this myself, but I'm quite busy.

**Comment by davidhedley** [comment]
Yes it is entirely possible. Just search through the fontforge source and anywhere you see: `time(&now);` add: `now=0;` after it. You will then get identical binaries etc after each generation.
