### ISSUE TITLE
[SOLVED] "Image format not supported: jpg" 

### ISSUE THREAD

**Issue by ionbegoechea** [coolwanglu/pdf2htmlEX#712]
Hello, I installed pdf2htmlex on ubuntu16.04.
I have also installed the libjpeg libraries of poppler.
 when run the comand: `pdf2htmlEX --bg-format jpg` i get the error:

> Image format not supported: jpg

The png and svg formats work fine. 
What can be missing?
 thanks.

**Comment by kjk** [comment]
Looking at the code (https://github.com/coolwanglu/pdf2htmlEX/blob/271bd3aeb25e33ad466a804b53c277d26256a0e1/src/BackgroundRenderer/SplashBackgroundRenderer.cc#L219) your pdf2htmlex must have been compiled without ENABLE_LIBJPEG option.

You would have to raise the issue with whoever compiled the code.

**Comment by ionbegoechea** [comment]
Hi, thanks for your response,
I compile pdf2htmlEX this way:
```
    git clone --depth 1 https://github.com/coolwanglu/pdf2htmlEX.git
    cd pdf2htmlEX/
    cmake .
    make
    sudo make install
```
How can I compile pdf2htmlEX again with the option ENABLE_LIBJPEG ?

Thanks.

**Comment by ionbegoechea** [comment]
Hi, solve the problem  **recompiling poppler and pdf2htmlEX** with the `ENABLE_LIBJPEG = ON` option.
Thank you very much!
