### ISSUE TITLE
How it is project different from "pdftohtml"?

### ISSUE THREAD

**Issue by hargup** [coolwanglu/pdf2htmlEX#720]
There exist similar and older tool called [pdftohtml](http://pdftohtml.sourceforge.net/), how is this project different from that?

**Comment by wanminliu** [comment]
The following is taken from Section 3.4 of the paper _[Online publishing via pdf2htmlEX](http://coolwanglu.github.io/pdf2htmlEX/doc/tb108wang.html)_.

> Prior to pdf2htmlEX, the pdftohtml utility from Poppler is probably the best known tool that is freely available to the community. While pdftohtml focuses more on extracting semantic information, pdf2htmlEX focuses on precise layout and appearance. 

To see the difference, you might convert this standard math PDF _[Edinburgh Lectures on Geometry, Analysis and Physics](https://arxiv.org/pdf/1009.4827)_ by using each tool.
